'use client'

import type { SchemaReactComponents } from '@formily/react'
import { FormItem } from '../form-item'
import {
  FormilyArrayField,
  FormilyCaptcha,
  FormilyCascader,
  FormilyCheckbox,
  FormilyDatePicker,
  FormilyDateRangePicker,
  FormilyDateTimePicker,
  FormilyDigit,
  FormilyDigitRange,
  FormilyInput,
  FormilyMoney,
  FormilyObjectField,
  FormilyPassword,
  FormilyProFormSection,
  FormilyRadio,
  FormilyRate,
  FormilySegmented,
  FormilySelect,
  FormilySlider,
  FormilySwitch,
  FormilyTextarea,
  FormilyTimePicker,
  FormilyTreeSelect,
  FormilyUpload,
  FormilyVisualCaptcha,
} from '../formily-fields'

export const defaultSchemaComponents: SchemaReactComponents = {
  FormItem,
  Input: FormilyInput,
  Password: FormilyPassword,
  Textarea: FormilyTextarea,
  Select: FormilySelect,
  Checkbox: FormilyCheckbox,
  Switch: FormilySwitch,
  Radio: FormilyRadio,
  DatePicker: FormilyDatePicker,
  DateRangePicker: FormilyDateRangePicker,
  DateTimePicker: FormilyDateTimePicker,
  TimePicker: FormilyTimePicker,
  Digit: FormilyDigit,
  DigitRange: FormilyDigitRange,
  Slider: FormilySlider,
  Rate: FormilyRate,
  Segmented: FormilySegmented,
  Cascader: FormilyCascader,
  TreeSelect: FormilyTreeSelect,
  Upload: FormilyUpload,
  Captcha: FormilyCaptcha,
  VisualCaptcha: FormilyVisualCaptcha,
  Money: FormilyMoney,
  ArrayField: FormilyArrayField,
  ObjectField: FormilyObjectField,
  ProFormSection: FormilyProFormSection,
}
