export type BlockFile = {
  /** Relative path shown in file tree, e.g. "pro-table/index.tsx" */
  target: string
  /** Absolute path on disk (resolved in generate script) */
  src: string
}

export type BlockDef = {
  name: string
  description: string
  iframeHeight?: string
  /** Source files to show in code panel (demo + component files) */
  files: BlockFile[]
}

export type Category = {
  id: string
  label: string
  blocks: BlockDef[]
}

// Helper to expand component files
function componentFiles(componentDir: string, fileNames: string[]): BlockFile[] {
  return fileNames.map((f) => ({
    target: `${componentDir}/${f}`,
    src: `../../packages/registry/pro/${componentDir}/${f}`,
  }))
}

function demoFile(name: string): BlockFile {
  return {
    target: `examples/${name}.tsx`,
    src: `registry/new-york-v4/examples/${name}.tsx`,
  }
}

const proTableFiles = [
  'index.tsx',
  'types.ts',
  'types/column.ts',
  'types/state.ts',
  'types/toolbar.ts',
  'types/table.ts',
  'table/data-table.tsx',
  'table/request-table.tsx',
  'table/view.tsx',
  'table/view-bulk-actions.tsx',
  'table/view-header.tsx',
  'table/view-toolbar.tsx',
  'table/view-types.ts',
  'table/content.tsx',
  'table/content-frame.tsx',
  'table/classes.ts',
  'table/element-types.ts',
  'table/elements.tsx',
  'hooks/column-filter.ts',
  'hooks/ranked-row-model.ts',
  'hooks/use-table.ts',
  'hooks/use-table-instance.ts',
  'hooks/use-table-pagination.ts',
  'hooks/use-table-state-handlers.ts',
  'hooks/use-table-ui-state.ts',
  'hooks/use-table-drag-sort.ts',
  'hooks/use-table-view-state.ts',
  'hooks/use-table-column-state.ts',
  'hooks/use-table-columns.ts',
  'table/column-align.ts',
  'table/column-state.ts',
  'table/column-utils.ts',
  'table/drag-sort.ts',
  'table/pinning.ts',
  'table/pinning-offsets.ts',
  'table/pinning-observer.ts',
  'table/system-columns.ts',
  'table/state.ts',
  'table/empty-state.tsx',
  'table/empty-row.tsx',
  'table/skeleton.tsx',
  'table/sortable-row.tsx',
  'table/header.tsx',
  'table/header-cell.tsx',
  'table/sort-indicator.tsx',
  'table/body.tsx',
  'table/body-cell.tsx',
  'table/body-row.tsx',
  'table/body-rows.tsx',
  'table/columns.tsx',
  'toolbar/index.tsx',
  'toolbar/classes.ts',
  'toolbar/auto-filter-cell.tsx',
  'toolbar/column-settings/button.tsx',
  'toolbar/column-settings/content.tsx',
  'toolbar/column-settings/header.tsx',
  'toolbar/column-settings/item.tsx',
  'toolbar/column-settings/list.tsx',
  'toolbar/column-settings/pinning-toggle.tsx',
  'toolbar/column-settings/use-column-settings-drag.ts',
  'toolbar/column-settings/utils.ts',
  'toolbar/columns-item.tsx',
  'toolbar/density-item.tsx',
  'toolbar/filter-items.tsx',
  'toolbar/left-items.tsx',
  'toolbar/refresh-item.tsx',
  'toolbar/reset-item.tsx',
  'toolbar/right-items.tsx',
  'toolbar/search-item.tsx',
  'toolbar/types.ts',
  'toolbar/utils.ts',
  'toolbar/bulk-actions/index.tsx',
  'toolbar/bulk-actions/keyboard.ts',
  'toolbar/bulk-actions/summary.tsx',
  'toolbar/bulk-actions/use-announcement.ts',
  'pagination/index.tsx',
  'pagination/classes.ts',
  'pagination/elements.tsx',
  'pagination/navigation.tsx',
  'pagination/navigation-control.tsx',
  'pagination/navigation-link.tsx',
  'pagination/page-range.tsx',
  'pagination/page-size.tsx',
  'pagination/quick-jump.tsx',
  'pagination/total.tsx',
  'pagination/types.ts',
  'pagination/utils.ts',
  'hooks/use-pro-table-url-state.ts',
  'hooks/url-state/config.ts',
  'hooks/url-state/parse.ts',
  'hooks/url-state/patch.ts',
  'hooks/url-state/types.ts',
]

const proFormFiles = [
  'index.tsx',
  'classes.ts',
  'form.tsx',
  'types.ts',
  'submitter-types.ts',
  'submitter-slots.tsx',
  'submitter.tsx',
  'use-form-instance.ts',
  'use-pro-form.ts',
  'layout/index.tsx',
  'layout/classes.ts',
  'layout/types.ts',
  'layout/utils.ts',
  'layout/action-buttons.tsx',
  'layout/action-types.ts',
  'layout/actions.tsx',
  'layout/section.tsx',
  'schema/enum-options.ts',
  'schema/infer-component.ts',
  'schema/index.tsx',
  'schema/normalize.ts',
  'schema/types.ts',
  'schema/validator.ts',
  'schema/components.tsx',
  'schema/field.tsx',
  'schema/content.tsx',
  'form-item-help.tsx',
  'form-item-label.tsx',
  'form-item.tsx',
  'overlay-form/index.tsx',
  'overlay-form/drawer-form.tsx',
  'overlay-form/modal-form.tsx',
  'overlay-form/classes.ts',
  'overlay-form/element-types.ts',
  'overlay-form/drawer-elements.tsx',
  'overlay-form/modal-elements.tsx',
  'overlay-form/content.tsx',
  'overlay-form/submitter.tsx',
  'overlay-form/types.ts',
  'overlay-form/use-overlay-form.ts',
  'formily-fields/index.tsx',
  'formily-fields/classes.ts',
  'formily-fields/field.ts',
  'formily-fields/date-value.ts',
  'formily-fields/labels.ts',
  'formily-fields/format.ts',
  'formily-fields/read-pretty.tsx',
  'formily-fields/text.tsx',
  'formily-fields/choice-read-pretty.tsx',
  'formily-fields/choice.tsx',
  'formily-fields/date.tsx',
  'formily-fields/numeric-read-pretty.tsx',
  'formily-fields/numeric.tsx',
  'formily-fields/upload-read-pretty.tsx',
  'formily-fields/advanced.tsx',
  'formily-fields/schema.tsx',
]

const proBaseFiles = [
  'hooks/use-copy.ts',
  'hooks/use-composed-ref.ts',
  'hooks/use-countdown.ts',
  'hooks/use-faceted-filter.ts',
  'hooks/use-fullscreen.ts',
  'utils/react-node.ts',
  'badge/index.tsx',
  'badge/variants.ts',
  'button/classes.ts',
  'button/index.tsx',
  'button/variants.ts',
  'button/tooltip.tsx',
  'button/copy.tsx',
  'button/fullscreen.tsx',
  'button/refresh.tsx',
  'label/classes.ts',
  'label/index.tsx',
  'separator/classes.ts',
  'separator/index.tsx',
  'command-menu/classes.ts',
  'command-menu/index.tsx',
  'command-menu/types.ts',
  'dropdown-menu/classes.ts',
  'dropdown-menu/index.tsx',
  'dropdown-menu/types.ts',
  'filter/faceted-filter/index.tsx',
  'filter/faceted-filter/options.tsx',
  'filter/faceted-filter/trigger.tsx',
  'filter/faceted-filter/types.ts',
]

const proEditorFiles = [
  'index.tsx',
  'classes.ts',
  'editor-content.tsx',
  'editor-pane.tsx',
  'editor-shell.tsx',
  'editor-toolbar-section.tsx',
  'preview-pane.tsx',
  'use-editor-state.ts',
  'use-editor-value.ts',
  'use-monaco-editor.ts',
  'preview-state.ts',
  'layout.ts',
  'core-types.ts',
  'toolbar/index.tsx',
  'toolbar/actions.tsx',
  'toolbar/options.ts',
  'toolbar/right-items.tsx',
  'toolbar/types.ts',
  'preview/scroll-sync.ts',
  'preview/styles.ts',
  'preview/types.ts',
  'language/index.ts',
  'types.ts',
  'monaco/index.ts',
  'monaco/shiki.ts',
  'monaco/theme.ts',
  'monaco/typescript.ts',
]

const codeViewerFiles = [
  'code/index.tsx',
  'code/classes.ts',
  'code/header.tsx',
  'code/fold-button.tsx',
  'code/table.tsx',
  'code/table-row.tsx',
  'code/status.tsx',
  'code/lines.ts',
  'code/types.ts',
  'code/use-code-viewer.ts',
  'shared/syntax.ts',
]

const markdownViewerFiles = [
  'markdown/index.tsx',
  'markdown/alert-element.tsx',
  'markdown/alert-style.tsx',
  'markdown/alert.tsx',
  'markdown/block-elements.tsx',
  'markdown/classes.ts',
  'markdown/code.tsx',
  'markdown/components.tsx',
  'markdown/elements.tsx',
  'markdown/github-alerts.ts',
  'markdown/headings.tsx',
  'markdown/inline-elements.tsx',
  'markdown/math-code-blocks.ts',
  'markdown/plugins.ts',
  'markdown/sanitize-schema.ts',
  'markdown/table.tsx',
  'markdown/types.ts',
  'markdown/utils.ts',
  'markdown/viewer.tsx',
  ...codeViewerFiles,
]

const imageViewerFiles = [
  'image/index.tsx',
  'image/classes.ts',
  'image/nav.tsx',
  'image/portal.tsx',
  'image/stage.tsx',
  'image/state.ts',
  'image/types.ts',
  'image/use-image-drag.ts',
  'image/use-image-keyboard.ts',
  'image/use-image-transform.ts',
  'image/use-image-viewer.ts',
  'image/toolbar.tsx',
  'image/toolbar-button.tsx',
  'image/toolbar-items.tsx',
  'image/toolbar-items-center.tsx',
  'image/toolbar-items-left.tsx',
  'image/toolbar-items-right.tsx',
  'image/thumbnails.tsx',
]

const diffViewerFiles = [
  'diff/index.tsx',
  'diff/classes.ts',
  'diff/content.tsx',
  'diff/header.tsx',
  'diff/line-cell.tsx',
  'diff/split-pane.tsx',
  'diff/table.tsx',
  'diff/use-diff-highlight.ts',
  'diff/utils.ts',
  'shared/syntax.ts',
]

const htmlViewerFiles = ['html/classes.ts', 'html/index.tsx']

const inputFieldFiles = [
  'shared/field.tsx',
  'shared/classes.ts',
  'shared/change-event.ts',
  'shared/select.tsx',
  'shared/select-classes.ts',
  'shared/select-content.tsx',
  'shared/select-item.tsx',
  'input/index.tsx',
  'input/affix.tsx',
  'input/affix-types.ts',
  'input/classes.ts',
  'input/clear.ts',
  'input/types.ts',
  'input/affix-utils.ts',
  'input/affix-value.ts',
  'input/affix-select.tsx',
  'input/use-affix-selection.ts',
  'input/use-input-affix.ts',
  'input/use-input-value.ts',
  'password/index.tsx',
  'password/types.ts',
]
const textareaFieldFiles = [
  'shared/field.tsx',
  'shared/change-event.ts',
  'shared/use-clearable-field.ts',
  'textarea/index.tsx',
  'textarea/classes.ts',
  'textarea/types.ts',
]
const numberFieldFiles = [
  'shared/number.ts',
  'digit/index.tsx',
  'digit/types.ts',
  'digit-range/classes.ts',
  'digit-range/index.tsx',
  'digit-range/types.ts',
]
const dateTimeFieldFiles = [
  'date-time-picker/content.tsx',
  'date-time-picker/classes.ts',
  'date-time-picker/index.tsx',
  'date-time-picker/time-select.tsx',
  'date-time-picker/trigger.tsx',
  'date-time-picker/types.ts',
  'time-picker/classes.ts',
  'time-picker/index.tsx',
  'time-picker/time-part-select.tsx',
  'time-picker/types.ts',
  'time-picker/utils.ts',
]
const selectFieldFiles = [
  'shared/trigger.tsx',
  'select/classes.ts',
  'select/content.tsx',
  'select/index.tsx',
  'select/multi-select.tsx',
  'select/multi-trigger.tsx',
  'select/single-select.tsx',
  'select/single-trigger.tsx',
  'select/types.ts',
  'select/command-options.tsx',
  'select/use-select.tsx',
  'select/utils.tsx',
]
const checkboxFieldFiles = [
  'checkbox/index.tsx',
  'checkbox/classes.ts',
  'checkbox/control.tsx',
  'checkbox/group.tsx',
  'checkbox/use-checkbox-group.ts',
  'checkbox/types.ts',
]
const cascaderFieldFiles = [
  'shared/trigger.tsx',
  'cascader/classes.ts',
  'cascader/index.tsx',
  'cascader/panel.tsx',
  'cascader/types.ts',
  'cascader/utils.ts',
]
const facetedFilterFieldFiles = [
  'faceted-filter/classes.ts',
  'faceted-filter/index.tsx',
  'faceted-filter/options.tsx',
  'faceted-filter/trigger.tsx',
  'faceted-filter/types.ts',
]
const treeSelectFieldFiles = [
  'shared/trigger.tsx',
  'tree-select/classes.ts',
  'tree-select/expand-button.tsx',
  'tree-select/index.tsx',
  'tree-select/option-button.tsx',
  'tree-select/tree-node.tsx',
  'tree-select/types.ts',
  'tree-select/utils.ts',
]
const uploadFieldFiles = [
  'upload/classes.ts',
  'upload/file-list.tsx',
  'upload/image-upload.tsx',
  'upload/index.tsx',
  'upload/upload.tsx',
  'upload/trigger-types.ts',
  'upload/input-trigger.tsx',
  'upload/compact-trigger.tsx',
  'upload/dropzone-trigger.tsx',
  'upload/state.ts',
  'upload/types.ts',
  'upload/use-upload.ts',
  'upload/use-upload-actions.ts',
  'upload/use-upload-drag.ts',
  'upload/use-upload-files.ts',
  'upload/upload-file.ts',
  'upload/url-file.ts',
  'upload/utils.ts',
]
const captchaFieldFiles = [
  'captcha/index.tsx',
  'captcha/classes.ts',
  'captcha/sms/index.tsx',
  'captcha/sms/send-button.tsx',
  'captcha/sms/types.ts',
  'captcha/visual/index.tsx',
  'captcha/visual/types.ts',
  'captcha/visual/visual-addon.tsx',
]
const arrayFieldFiles = [
  'array-field/index.tsx',
  'array-field/classes.ts',
  'array-field/sortable-item.tsx',
  'array-field/types.ts',
  'array-field/use-array-field-ids.ts',
  'array-field/use-array-field-sensors.ts',
  'array-field/use-array-field.ts',
]
const objectFieldFiles = [
  'object-field/classes.ts',
  'object-field/index.tsx',
  'object-field/body.tsx',
  'object-field/collapsible.tsx',
  'object-field/content.tsx',
  'object-field/header.tsx',
  'object-field/types.ts',
  'object-field/utils.ts',
]

export const CATEGORIES: Category[] = [
  {
    id: 'pro-base',
    label: 'ProBase',
    blocks: [
      {
        name: 'pro-base-demo',
        description: 'Shared primitives for button, copy feedback, loading, and fullscreen state.',
        iframeHeight: '240px',
        files: [demoFile('pro-base-demo'), ...componentFiles('base', proBaseFiles)],
      },
    ],
  },
  {
    id: 'pro-table',
    label: 'ProTable',
    blocks: [
      {
        name: 'pro-table-demo',
        description: 'Full-featured data table with filtering, sorting, and pagination.',
        iframeHeight: '676px',
        files: [demoFile('pro-table-demo'), ...componentFiles('table', proTableFiles)],
      },

      {
        name: 'pro-table-drag-sort-demo',
        description: 'Drag-and-drop row reordering with dnd-kit.',
        iframeHeight: '536px',
        files: [demoFile('pro-table-drag-sort-demo'), ...componentFiles('table', proTableFiles)],
      },
    ],
  },
  {
    id: 'pro-form',
    label: 'ProForm',
    blocks: [
      {
        name: 'pro-form-demo',
        description: 'Schema-driven form builder with submit actions.',
        iframeHeight: '537px',
        files: [demoFile('pro-form-demo'), ...componentFiles('form', proFormFiles)],
      },
      {
        name: 'pro-form-linkage-demo',
        description: 'Dynamic field linkage — show/hide/disable based on other values.',
        iframeHeight: '481px',
        files: [demoFile('pro-form-linkage-demo'), ...componentFiles('form', proFormFiles)],
      },
      {
        name: 'pro-form-validation-demo',
        description:
          'Schema validation with native rules, optional Zod validators, and real-time error messages.',
        iframeHeight: '500px',
        files: [demoFile('pro-form-validation-demo'), ...componentFiles('form', proFormFiles)],
      },
      {
        name: 'pro-form-modal-demo',
        description: 'ModalForm — schema-driven form inside a Dialog, closes on successful submit.',
        iframeHeight: '480px',
        files: [demoFile('pro-form-modal-demo'), ...componentFiles('form', proFormFiles)],
      },
      {
        name: 'pro-form-drawer-demo',
        description:
          'DrawerForm — schema-driven form inside a Drawer panel, closes on successful submit.',
        iframeHeight: '480px',
        files: [demoFile('pro-form-drawer-demo'), ...componentFiles('form', proFormFiles)],
      },
    ],
  },
  {
    id: 'pro-descriptions',
    label: 'ProDescriptions',
    blocks: [
      {
        name: 'pro-descriptions-demo',
        description: 'Structured key-value descriptions with inline view/edit mode switching.',
        iframeHeight: '336px',
        files: [
          demoFile('pro-descriptions-demo'),
          ...componentFiles('descriptions', [
            'index.tsx',
            'item.tsx',
            'styles.ts',
            'types.ts',
            'utils.ts',
          ]),
        ],
      },
    ],
  },
  {
    id: 'pro-editor',
    label: 'ProEditor',
    blocks: [
      {
        name: 'pro-editor-demo',
        description:
          'Monaco-powered code editor with externally controlled language, syntax theme, format, and live preview.',
        iframeHeight: '490px',
        files: [demoFile('pro-editor-demo'), ...componentFiles('editor', proEditorFiles)],
      },
      {
        name: 'pro-editor-monaco-demo',
        description: 'Edit-only Monaco editor without a preview renderer or preview mode controls.',
        iframeHeight: '430px',
        files: [demoFile('pro-editor-monaco-demo'), ...componentFiles('editor', proEditorFiles)],
      },
      {
        name: 'pro-editor-markdown-demo',
        description: 'Markdown mode with full GFM syntax highlighting powered by Monaco.',
        iframeHeight: '490px',
        files: [
          demoFile('pro-editor-markdown-demo'),
          ...componentFiles('editor', proEditorFiles),
          ...componentFiles('viewer', markdownViewerFiles),
        ],
      },
    ],
  },
  {
    id: 'pro-viewer',
    label: 'ProViewer',
    blocks: [
      {
        name: 'markdown-viewer-demo',
        description: 'Render Markdown with GFM syntax, tables, and code blocks.',
        iframeHeight: '674px',
        files: [demoFile('markdown-viewer-demo'), ...componentFiles('viewer', markdownViewerFiles)],
      },
      {
        name: 'code-viewer-demo',
        description: 'Syntax-highlighted code viewer with copy button.',
        iframeHeight: '775px',
        files: [demoFile('code-viewer-demo'), ...componentFiles('viewer', codeViewerFiles)],
      },
      {
        name: 'json-viewer-demo',
        description: 'Collapsible JSON tree viewer with search and copy.',
        iframeHeight: '719px',
        files: [demoFile('json-viewer-demo')],
      },
      {
        name: 'image-viewer-demo',
        description: 'Image viewer with zoom, pan, rotate, and fullscreen.',
        iframeHeight: '653px',
        files: [demoFile('image-viewer-demo'), ...componentFiles('viewer', imageViewerFiles)],
      },
      {
        name: 'diff-viewer-demo',
        description: 'Side-by-side diff viewer with line-level highlighting.',
        iframeHeight: '766px',
        files: [demoFile('diff-viewer-demo'), ...componentFiles('viewer', diffViewerFiles)],
      },
      {
        name: 'html-viewer-demo',
        description: 'Sandboxed HTML preview surface for rendering raw HTML snippets.',
        iframeHeight: '360px',
        files: [demoFile('html-viewer-demo'), ...componentFiles('viewer', htmlViewerFiles)],
      },
    ],
  },
  {
    id: 'pro-fields',
    label: 'ProFields',
    blocks: [
      {
        name: 'pro-fields-demo',
        description: 'Advanced field types: select, date, switch, and more.',
        iframeHeight: '388px',
        files: [
          demoFile('pro-fields-demo'),
          ...componentFiles('base/fields', [
            ...inputFieldFiles,
            ...selectFieldFiles,
            ...checkboxFieldFiles,
            'switch/index.tsx',
            'switch/classes.ts',
            'switch/types.ts',
            ...textareaFieldFiles,
            'radio/index.tsx',
            'radio/classes.ts',
            'radio/item.tsx',
            'radio/types.ts',
            'shared/calendar.tsx',
            'shared/calendar-class-names.ts',
            'shared/calendar-day-button.tsx',
            'shared/date.ts',
            'shared/popover.tsx',
            'date-picker/index.tsx',
            'date-picker/types.ts',
            'date-range-picker/index.tsx',
            'date-range-picker/types.ts',
            ...dateTimeFieldFiles,
            ...numberFieldFiles,
            'slider/index.tsx',
            'slider/classes.ts',
            'slider/types.ts',
            'rate/index.tsx',
            'rate/classes.ts',
            'rate/star.tsx',
            'rate/types.ts',
            'segmented/index.tsx',
            'segmented/classes.ts',
            'segmented/types.ts',
            ...cascaderFieldFiles,
            ...treeSelectFieldFiles,
            ...uploadFieldFiles,
            ...captchaFieldFiles,
            'money/index.tsx',
            'money/types.ts',
            ...arrayFieldFiles,
            ...objectFieldFiles,
          ]),
          ...componentFiles('base/hooks', ['use-countdown.ts', 'use-faceted-filter.ts']),
          ...componentFiles('base/filter', facetedFilterFieldFiles),
        ],
      },
      {
        name: 'pro-input-demo',
        description: 'Enhanced input with prefix, suffix, clear, and character count.',
        iframeHeight: '264px',
        files: [demoFile('pro-input-demo'), ...componentFiles('base/fields', inputFieldFiles)],
      },
      {
        name: 'pro-fields-slider-demo',
        description: 'Slider field with min/max, step, and value display.',
        iframeHeight: '240px',
        files: [
          demoFile('pro-fields-slider-demo'),
          ...componentFiles('base/fields', [
            'slider/index.tsx',
            'slider/classes.ts',
            'slider/types.ts',
          ]),
        ],
      },
      {
        name: 'pro-fields-rate-demo',
        description: 'Star rating field with half-star support.',
        iframeHeight: '252px',
        files: [
          demoFile('pro-fields-rate-demo'),
          ...componentFiles('base/fields', [
            'rate/index.tsx',
            'rate/classes.ts',
            'rate/star.tsx',
            'rate/types.ts',
          ]),
        ],
      },
      {
        name: 'pro-fields-segmented-demo',
        description: 'Segmented control for mutually exclusive options.',
        iframeHeight: '212px',
        files: [
          demoFile('pro-fields-segmented-demo'),
          ...componentFiles('base/fields', [
            'segmented/index.tsx',
            'segmented/classes.ts',
            'segmented/types.ts',
          ]),
        ],
      },
      {
        name: 'pro-fields-faceted-filter-demo',
        description: 'Faceted filter with single-select, multi-select, and facet counts.',
        iframeHeight: '224px',
        files: [
          demoFile('pro-fields-faceted-filter-demo'),
          ...componentFiles('base/hooks', ['use-faceted-filter.ts']),
          ...componentFiles('base/filter', facetedFilterFieldFiles),
        ],
      },
      {
        name: 'pro-fields-cascader-demo',
        description: 'Multi-level cascader select for hierarchical data.',
        iframeHeight: '128px',
        files: [
          demoFile('pro-fields-cascader-demo'),
          ...componentFiles('base/fields', cascaderFieldFiles),
        ],
      },
      {
        name: 'pro-fields-tree-select-demo',
        description: 'Tree-structured select with search and multi-select.',
        iframeHeight: '208px',
        files: [
          demoFile('pro-fields-tree-select-demo'),
          ...componentFiles('base/fields', treeSelectFieldFiles),
        ],
      },
      {
        name: 'pro-fields-upload-demo',
        description: 'File upload field with drag-and-drop and preview.',
        iframeHeight: '352px',
        files: [
          demoFile('pro-fields-upload-demo'),
          ...componentFiles('base/fields', uploadFieldFiles),
        ],
      },
      {
        name: 'pro-fields-captcha-demo',
        description: 'Captcha input with countdown send button.',
        iframeHeight: '128px',
        files: [
          demoFile('pro-fields-captcha-demo'),
          ...componentFiles('base/hooks', ['use-countdown.ts']),
          ...componentFiles('base/fields', captchaFieldFiles),
        ],
      },
      {
        name: 'pro-fields-money-demo',
        description: 'Money input with currency symbol and locale formatting.',
        iframeHeight: '288px',
        files: [
          demoFile('pro-fields-money-demo'),
          ...componentFiles('base/fields', [
            'money/index.tsx',
            'money/types.ts',
            ...inputFieldFiles,
          ]),
        ],
      },
    ],
  },
]
