// One Dark Pro Flat — dark + One Light derived variant
// Token structure mirrors Dracula (brijeshb42/monaco-themes) with One Dark Pro colors
// Light: Atom One Light palette equivalents
// Chrome colors injected at runtime by applyShadcnTheme() from shadcn CSS vars

import type { editor } from 'monaco-editor'

type MonacoThemeData = editor.IStandaloneThemeData

export const oneDarkProFlatTheme: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { background: '282c34', token: '' },
    { foreground: '5c6370', fontStyle: 'italic', token: 'comment' },
    { foreground: '5c6370', fontStyle: 'italic', token: 'punctuation.definition.comment' },
    { foreground: '98c379', token: 'string' },
    { foreground: '56b6c2', token: 'constant.numeric' },
    { foreground: '56b6c2', token: 'constant.language' },
    { foreground: '56b6c2', token: 'constant.character' },
    { foreground: '56b6c2', token: 'constant.other' },
    { foreground: 'd19a66', token: 'variable.other.readwrite.instance' },
    { foreground: 'c678dd', token: 'constant.character.escaped' },
    { foreground: 'c678dd', token: 'constant.character.escape' },
    { foreground: 'c678dd', token: 'string source' },
    { foreground: 'c678dd', token: 'keyword' },
    { foreground: 'c678dd', token: 'storage' },
    { foreground: 'e5c07b', fontStyle: 'italic', token: 'storage.type' },
    { foreground: 'e5c07b', fontStyle: 'underline', token: 'entity.name.class' },
    { foreground: 'e5c07b', fontStyle: 'italic underline', token: 'entity.other.inherited-class' },
    { foreground: '61afef', token: 'entity.name.function' },
    { foreground: 'd19a66', fontStyle: 'italic', token: 'variable.parameter' },
    { foreground: 'e06c75', token: 'entity.name.tag' },
    { foreground: 'd19a66', token: 'entity.other.attribute-name' },
    { foreground: '61afef', token: 'support.function' },
    { foreground: '56b6c2', token: 'support.constant' },
    { foreground: '56b6c2', fontStyle: 'italic', token: 'support.type' },
    { foreground: '56b6c2', fontStyle: 'italic', token: 'support.class' },
    { foreground: 'abb2bf', background: 'e06c75', token: 'invalid' },
    { foreground: 'abb2bf', background: 'c678dd', token: 'invalid.deprecated' },
    { foreground: 'abb2bf', token: 'meta.structure.dictionary.json string.quoted.double.json' },
    { foreground: '5c6370', token: 'meta.diff' },
    { foreground: '5c6370', token: 'meta.diff.header' },
    { foreground: 'e06c75', token: 'markup.deleted' },
    { foreground: '98c379', token: 'markup.inserted' },
    { foreground: 'e5c07b', token: 'markup.changed' },
    { foreground: '56b6c2', token: 'constant.numeric.line-number.find-in-files - match' },
    { foreground: 'e5c07b', token: 'entity.name.filename' },
    { foreground: 'e06c75', token: 'message.error' },
    {
      foreground: 'abb2bf',
      token: 'punctuation.definition.string.begin.json - meta.structure.dictionary.value.json',
    },
    {
      foreground: 'abb2bf',
      token: 'punctuation.definition.string.end.json - meta.structure.dictionary.value.json',
    },
    { foreground: '61afef', token: 'meta.structure.dictionary.json string.quoted.double.json' },
    {
      foreground: '98c379',
      token: 'meta.structure.dictionary.value.json string.quoted.double.json',
    },
    {
      foreground: '98c379',
      token: 'meta meta meta meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: 'd19a66',
      token: 'meta meta meta meta meta meta.structure.dictionary.value string',
    },
    { foreground: 'e06c75', token: 'meta meta meta meta meta.structure.dictionary.value string' },
    { foreground: 'c678dd', token: 'meta meta meta meta.structure.dictionary.value string' },
    { foreground: '98c379', token: 'meta meta meta.structure.dictionary.value string' },
    { foreground: 'd19a66', token: 'meta meta.structure.dictionary.value string' },
  ],
  colors: {},
  tokenColors: [],
}

export const oneLightProFlatTheme: MonacoThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { background: 'fafafa', token: '' },
    { foreground: 'a0a1a7', fontStyle: 'italic', token: 'comment' },
    { foreground: 'a0a1a7', fontStyle: 'italic', token: 'punctuation.definition.comment' },
    { foreground: '50a14f', token: 'string' },
    { foreground: '0184bc', token: 'constant.numeric' },
    { foreground: '0184bc', token: 'constant.language' },
    { foreground: '0184bc', token: 'constant.character' },
    { foreground: '0184bc', token: 'constant.other' },
    { foreground: '986801', token: 'variable.other.readwrite.instance' },
    { foreground: 'a626a4', token: 'constant.character.escaped' },
    { foreground: 'a626a4', token: 'constant.character.escape' },
    { foreground: 'a626a4', token: 'string source' },
    { foreground: 'a626a4', token: 'keyword' },
    { foreground: 'a626a4', token: 'storage' },
    { foreground: 'c18401', fontStyle: 'italic', token: 'storage.type' },
    { foreground: 'c18401', fontStyle: 'underline', token: 'entity.name.class' },
    { foreground: 'c18401', fontStyle: 'italic underline', token: 'entity.other.inherited-class' },
    { foreground: '4078f2', token: 'entity.name.function' },
    { foreground: '986801', fontStyle: 'italic', token: 'variable.parameter' },
    { foreground: 'e45649', token: 'entity.name.tag' },
    { foreground: '986801', token: 'entity.other.attribute-name' },
    { foreground: '4078f2', token: 'support.function' },
    { foreground: '0184bc', token: 'support.constant' },
    { foreground: '0184bc', fontStyle: 'italic', token: 'support.type' },
    { foreground: '0184bc', fontStyle: 'italic', token: 'support.class' },
    { foreground: '383a42', background: 'e45649', token: 'invalid' },
    { foreground: '383a42', background: 'a626a4', token: 'invalid.deprecated' },
    { foreground: '383a42', token: 'meta.structure.dictionary.json string.quoted.double.json' },
    { foreground: 'a0a1a7', token: 'meta.diff' },
    { foreground: 'a0a1a7', token: 'meta.diff.header' },
    { foreground: 'e45649', token: 'markup.deleted' },
    { foreground: '50a14f', token: 'markup.inserted' },
    { foreground: 'c18401', token: 'markup.changed' },
    { foreground: '0184bc', token: 'constant.numeric.line-number.find-in-files - match' },
    { foreground: 'c18401', token: 'entity.name.filename' },
    { foreground: 'e45649', token: 'message.error' },
    {
      foreground: '383a42',
      token: 'punctuation.definition.string.begin.json - meta.structure.dictionary.value.json',
    },
    {
      foreground: '383a42',
      token: 'punctuation.definition.string.end.json - meta.structure.dictionary.value.json',
    },
    { foreground: '4078f2', token: 'meta.structure.dictionary.json string.quoted.double.json' },
    {
      foreground: '50a14f',
      token: 'meta.structure.dictionary.value.json string.quoted.double.json',
    },
    {
      foreground: '50a14f',
      token: 'meta meta meta meta meta meta meta.structure.dictionary.value string',
    },
    {
      foreground: '986801',
      token: 'meta meta meta meta meta meta.structure.dictionary.value string',
    },
    { foreground: 'e45649', token: 'meta meta meta meta meta.structure.dictionary.value string' },
    { foreground: 'a626a4', token: 'meta meta meta meta.structure.dictionary.value string' },
    { foreground: '50a14f', token: 'meta meta meta.structure.dictionary.value string' },
    { foreground: '986801', token: 'meta meta.structure.dictionary.value string' },
  ],
  colors: {},
  tokenColors: [],
}
