// One Dark Pro Flat — dark and derived light variant
// Dark: colors from Binaryify/OneDark-Pro (MIT)
// Light: Atom One Light palette equivalents
// Rules use precise semantic Monaco tokens (not VS Code TextMate scopes)
// Chrome colors are injected at runtime by applyShadcnTheme() from shadcn CSS vars

import type { editor } from 'monaco-editor'

type MonacoThemeData = editor.IStandaloneThemeData

export const oneDarkProFlatTheme: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { background: '282c34', token: '' },
    { foreground: '5c6370', fontStyle: 'italic', token: 'comment' },
    { foreground: '5c6370', fontStyle: 'italic', token: 'punctuation.definition.comment' },
    { foreground: '98c379', token: 'string' },
    { foreground: '98c379', token: 'string.quoted' },
    { foreground: '98c379', token: 'string.template' },
    { foreground: '56b6c2', token: 'string.regexp' },
    { foreground: 'c678dd', token: 'keyword' },
    { foreground: 'c678dd', token: 'keyword.control' },
    { foreground: 'c678dd', token: 'keyword.operator' },
    { foreground: 'c678dd', token: 'keyword.other' },
    { foreground: 'c678dd', token: 'storage' },
    { foreground: 'c678dd', token: 'storage.type' },
    { foreground: 'e06c75', token: 'storage.modifier' },
    { foreground: 'd19a66', token: 'constant.numeric' },
    { foreground: 'd19a66', token: 'constant.language' },
    { foreground: 'd19a66', token: 'constant.character' },
    { foreground: 'd19a66', token: 'constant.other' },
    { foreground: '61afef', token: 'entity.name.function' },
    { foreground: '61afef', token: 'support.function' },
    { foreground: '61afef', token: 'meta.function-call' },
    { foreground: '61afef', token: 'meta.function-call.generic' },
    { foreground: 'e5c07b', token: 'entity.name.type' },
    { foreground: 'e5c07b', token: 'entity.name.class' },
    { foreground: 'e5c07b', token: 'entity.name.namespace' },
    { foreground: 'e5c07b', token: 'entity.other.inherited-class' },
    { foreground: 'e5c07b', token: 'support.class' },
    { foreground: 'e5c07b', token: 'support.type' },
    { foreground: 'e06c75', token: 'variable' },
    { foreground: 'e06c75', token: 'variable.other' },
    { foreground: 'abb2bf', token: 'variable.parameter' },
    { foreground: 'abb2bf', token: 'variable.other.object' },
    { foreground: '56b6c2', token: 'variable.language' },
    { foreground: 'e06c75', token: 'entity.name.tag' },
    { foreground: 'd19a66', token: 'entity.other.attribute-name' },
    { foreground: '56b6c2', token: 'keyword.operator.assignment' },
    { foreground: '56b6c2', token: 'keyword.operator.comparison' },
    { foreground: '56b6c2', token: 'keyword.operator.logical' },
    { foreground: '56b6c2', token: 'keyword.operator.arithmetic' },
    { foreground: 'e06c75', token: 'keyword.control.import' },
    { foreground: 'e06c75', token: 'keyword.control.export' },
    { foreground: 'e06c75', token: 'keyword.control.from' },
    { foreground: '61afef', token: 'meta.decorator' },
    { foreground: '61afef', token: 'punctuation.decorator' },
    { foreground: 'd19a66', token: 'support.type.property-name' },
    { foreground: 'd19a66', token: 'meta.object-literal.key' },
    { foreground: 'f8f8f0', background: 'f92672', token: 'invalid' },
    { foreground: 'f8f8f0', background: 'ae81ff', token: 'invalid.deprecated' },
  ],
  colors: {},
  tokenColors: [],
}

export const oneLightProFlatTheme: MonacoThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { background: 'fafafa', token: '' },
    { foreground: 'a0a1a7', fontStyle: 'italic', token: 'comment' },
    { foreground: 'a0a1a7', fontStyle: 'italic', token: 'punctuation.definition.comment' },
    { foreground: '50a14f', token: 'string' },
    { foreground: '50a14f', token: 'string.quoted' },
    { foreground: '50a14f', token: 'string.template' },
    { foreground: '0184bc', token: 'string.regexp' },
    { foreground: 'a626a4', token: 'keyword' },
    { foreground: 'a626a4', token: 'keyword.control' },
    { foreground: 'a626a4', token: 'keyword.operator' },
    { foreground: 'a626a4', token: 'keyword.other' },
    { foreground: 'a626a4', token: 'storage' },
    { foreground: 'a626a4', token: 'storage.type' },
    { foreground: 'e45649', token: 'storage.modifier' },
    { foreground: '986801', token: 'constant.numeric' },
    { foreground: '986801', token: 'constant.language' },
    { foreground: '986801', token: 'constant.character' },
    { foreground: '986801', token: 'constant.other' },
    { foreground: '4078f2', token: 'entity.name.function' },
    { foreground: '4078f2', token: 'support.function' },
    { foreground: '4078f2', token: 'meta.function-call' },
    { foreground: '4078f2', token: 'meta.function-call.generic' },
    { foreground: '986801', token: 'entity.name.type' },
    { foreground: '986801', token: 'entity.name.class' },
    { foreground: '986801', token: 'entity.name.namespace' },
    { foreground: '986801', token: 'entity.other.inherited-class' },
    { foreground: '986801', token: 'support.class' },
    { foreground: '986801', token: 'support.type' },
    { foreground: 'e45649', token: 'variable' },
    { foreground: 'e45649', token: 'variable.other' },
    { foreground: '383a42', token: 'variable.parameter' },
    { foreground: '383a42', token: 'variable.other.object' },
    { foreground: '0184bc', token: 'variable.language' },
    { foreground: 'e45649', token: 'entity.name.tag' },
    { foreground: '986801', token: 'entity.other.attribute-name' },
    { foreground: '0184bc', token: 'keyword.operator.assignment' },
    { foreground: '0184bc', token: 'keyword.operator.comparison' },
    { foreground: '0184bc', token: 'keyword.operator.logical' },
    { foreground: '0184bc', token: 'keyword.operator.arithmetic' },
    { foreground: 'e45649', token: 'keyword.control.import' },
    { foreground: 'e45649', token: 'keyword.control.export' },
    { foreground: 'e45649', token: 'keyword.control.from' },
    { foreground: '4078f2', token: 'meta.decorator' },
    { foreground: '4078f2', token: 'punctuation.decorator' },
    { foreground: '986801', token: 'support.type.property-name' },
    { foreground: '986801', token: 'meta.object-literal.key' },
    { foreground: '383a42', background: 'e45649', token: 'invalid' },
    { foreground: '383a42', background: 'a626a4', token: 'invalid.deprecated' },
  ],
  colors: {},
  tokenColors: [],
}
