import { defaultSchema } from 'rehype-sanitize'

export const sanitizeSchema = {
  ...defaultSchema,
  tagNames: [...(defaultSchema.tagNames ?? []), 'details', 'summary', 'kbd', 'sub', 'sup'],
  attributes: {
    ...defaultSchema.attributes,
    a: [...(defaultSchema.attributes?.a ?? []), 'className', 'target', 'rel'],
    code: [...(defaultSchema.attributes?.code ?? []), 'className'],
    div: [...(defaultSchema.attributes?.div ?? []), 'className', 'data-alert'],
    input: [...(defaultSchema.attributes?.input ?? []), 'type', 'checked', 'disabled'],
    span: [...(defaultSchema.attributes?.span ?? []), 'className', 'aria-hidden'],
    svg: [
      ...(defaultSchema.attributes?.svg ?? []),
      'className',
      'height',
      'role',
      'style',
      'viewBox',
      'width',
      'xmlns',
    ],
    path: [...(defaultSchema.attributes?.path ?? []), 'd', 'fill', 'stroke'],
    g: [...(defaultSchema.attributes?.g ?? []), 'fill', 'stroke', 'transform'],
    line: [
      ...(defaultSchema.attributes?.line ?? []),
      'stroke',
      'strokeWidth',
      'x1',
      'x2',
      'y1',
      'y2',
    ],
    rect: [
      ...(defaultSchema.attributes?.rect ?? []),
      'fill',
      'height',
      'rx',
      'ry',
      'stroke',
      'width',
      'x',
      'y',
    ],
    td: [...(defaultSchema.attributes?.td ?? []), 'align'],
    th: [...(defaultSchema.attributes?.th ?? []), 'align'],
  },
}
