// One Dark Pro Flat — dark and derived light variant
// Dark token colors sourced from github.com/Binaryify/OneDark-Pro (MIT)
// Light variant derived by mapping dark palette → Atom One Light equivalents
// Chrome colors (bg, widgets, scrollbar) are intentionally omitted here —
// applyShadcnTheme() reads them from shadcn CSS variables at runtime.

import type { editor } from 'monaco-editor'

type MonacoThemeData = editor.IStandaloneThemeData

export const oneDarkProFlatTheme: MonacoThemeData = {
  base: 'vs-dark',
  inherit: false,
  rules: [
    { token: 'meta.embedded', foreground: 'abb2bf' },
    {
      token:
        'punctuation.definition.delayed.unison,punctuation.definition.list.begin.unison,punctuation.definition.list.end.unison,punctuation.definition.ability.begin.unison,punctuation.definition.ability.end.unison,punctuation.operator.assignment.as.unison,punctuation.separator.pipe.unison,punctuation.separator.delimiter.unison,punctuation.definition.hash.unison',
      foreground: 'e06c75',
    },
    { token: 'variable.other.generic-type.haskell', foreground: 'c678dd' },
    { token: 'storage.type.haskell', foreground: 'd19a66' },
    { token: 'support.variable.magic.python', foreground: 'e06c75' },
    {
      token:
        'punctuation.separator.period.python,punctuation.separator.element.python,punctuation.parenthesis.begin.python,punctuation.parenthesis.end.python',
      foreground: 'abb2bf',
    },
    { token: 'variable.parameter.function.language.special.self.python', foreground: 'e5c07b' },
    { token: 'variable.parameter.function.language.special.cls.python', foreground: 'e5c07b' },
    { token: 'storage.modifier.lifetime.rust', foreground: 'abb2bf' },
    { token: 'support.function.std.rust', foreground: '61afef' },
    { token: 'entity.name.lifetime.rust', foreground: 'e5c07b' },
    { token: 'variable.language.rust', foreground: 'e06c75' },
    { token: 'support.constant.edge', foreground: 'c678dd' },
    { token: 'constant.other.character-class.regexp', foreground: 'e06c75' },
    { token: 'keyword.operator.word', foreground: 'c678dd' },
    { token: 'keyword.operator.quantifier.regexp', foreground: 'd19a66' },
    { token: 'variable.parameter.function', foreground: 'abb2bf' },
    { token: 'comment markup.link', foreground: '5c6370' },
    { token: 'markup.changed.diff', foreground: 'e5c07b' },
    {
      token:
        'meta.diff.header.from-file,meta.diff.header.to-file,punctuation.definition.from-file.diff,punctuation.definition.to-file.diff',
      foreground: '61afef',
    },
    { token: 'markup.inserted.diff', foreground: '98c379' },
    { token: 'markup.deleted.diff', foreground: 'e06c75' },
    { token: 'meta.function.c,meta.function.cpp', foreground: 'e06c75' },
    {
      token:
        'punctuation.section.block.begin.bracket.curly.cpp,punctuation.section.block.end.bracket.curly.cpp,punctuation.terminator.statement.c,punctuation.section.block.begin.bracket.curly.c,punctuation.section.block.end.bracket.curly.c,punctuation.section.parens.begin.bracket.round.c,punctuation.section.parens.end.bracket.round.c,punctuation.section.parameters.begin.bracket.round.c,punctuation.section.parameters.end.bracket.round.c',
      foreground: 'abb2bf',
    },
    { token: 'punctuation.separator.key-value', foreground: 'abb2bf' },
    { token: 'keyword.operator.expression.import', foreground: '61afef' },
    { token: 'support.constant.math', foreground: 'e5c07b' },
    { token: 'support.constant.property.math', foreground: 'd19a66' },
    { token: 'variable.other.constant', foreground: 'e5c07b' },
    { token: 'storage.type.annotation.java', foreground: 'e5c07b' },
    { token: 'storage.type.object.array.java', foreground: 'e5c07b' },
    { token: 'source.java', foreground: 'e06c75' },
    {
      token:
        'punctuation.section.block.begin.java,punctuation.section.block.end.java,punctuation.definition.method-parameters.begin.java,punctuation.definition.method-parameters.end.java,meta.method.identifier.java,punctuation.section.method.begin.java,punctuation.section.method.end.java,punctuation.terminator.java,punctuation.section.class.begin.java,punctuation.section.class.end.java,punctuation.section.inner-class.begin.java,punctuation.section.inner-class.end.java,meta.method-call.java,punctuation.section.class.begin.bracket.curly.java,punctuation.section.class.end.bracket.curly.java,punctuation.section.method.begin.bracket.curly.java,punctuation.section.method.end.bracket.curly.java,punctuation.separator.period.java,punctuation.bracket.angle.java,punctuation.definition.annotation.java,meta.method.body.java',
      foreground: 'abb2bf',
    },
    { token: 'meta.method.java', foreground: '61afef' },
    {
      token: 'storage.modifier.import.java,storage.type.java,storage.type.generic.java',
      foreground: 'e5c07b',
    },
    { token: 'keyword.operator.instanceof.java', foreground: 'c678dd' },
    { token: 'meta.definition.variable.name.java', foreground: 'e06c75' },
    { token: 'keyword.operator.logical', foreground: '56b6c2' },
    { token: 'keyword.operator.bitwise', foreground: '56b6c2' },
    { token: 'keyword.operator.channel', foreground: '56b6c2' },
    {
      token: 'support.constant.property-value.scss,support.constant.property-value.css',
      foreground: 'd19a66',
    },
    {
      token: 'keyword.operator.css,keyword.operator.scss,keyword.operator.less',
      foreground: '56b6c2',
    },
    {
      token:
        'support.constant.color.w3c-standard-color-name.css,support.constant.color.w3c-standard-color-name.scss',
      foreground: 'd19a66',
    },
    { token: 'punctuation.separator.list.comma.css', foreground: 'abb2bf' },
    { token: 'support.constant.color.w3c-standard-color-name.css', foreground: 'd19a66' },
    { token: 'support.type.vendored.property-name.css', foreground: '56b6c2' },
    {
      token: 'support.module.node,support.type.object.module,support.module.node',
      foreground: 'e5c07b',
    },
    { token: 'entity.name.type.module', foreground: 'e5c07b' },
    {
      token:
        'variable.other.readwrite,meta.object-literal.key,support.variable.property,support.variable.object.process,support.variable.object.node',
      foreground: 'e06c75',
    },
    { token: 'support.constant.json', foreground: 'd19a66' },
    { token: 'keyword.operator.expression.instanceof', foreground: 'c678dd' },
    { token: 'keyword.operator.new', foreground: 'c678dd' },
    { token: 'keyword.operator.ternary', foreground: 'c678dd' },
    { token: 'keyword.operator.optional', foreground: 'c678dd' },
    { token: 'keyword.operator.expression.keyof', foreground: 'c678dd' },
    { token: 'support.type.object.console', foreground: 'e06c75' },
    { token: 'support.variable.property.process', foreground: 'd19a66' },
    { token: 'entity.name.function,support.function.console', foreground: '61afef' },
    { token: 'keyword.operator.misc.rust', foreground: 'abb2bf' },
    { token: 'keyword.operator.sigil.rust', foreground: 'c678dd' },
    { token: 'keyword.operator.delete', foreground: 'c678dd' },
    { token: 'support.type.object.dom', foreground: '56b6c2' },
    { token: 'support.variable.dom,support.variable.property.dom', foreground: 'e06c75' },
    {
      token:
        'keyword.operator.arithmetic,keyword.operator.comparison,keyword.operator.decrement,keyword.operator.increment,keyword.operator.relational',
      foreground: '56b6c2',
    },
    {
      token:
        'keyword.operator.assignment.c,keyword.operator.comparison.c,keyword.operator.c,keyword.operator.increment.c,keyword.operator.decrement.c,keyword.operator.bitwise.shift.c,keyword.operator.assignment.cpp,keyword.operator.comparison.cpp,keyword.operator.cpp,keyword.operator.increment.cpp,keyword.operator.decrement.cpp,keyword.operator.bitwise.shift.cpp',
      foreground: 'c678dd',
    },
    { token: 'punctuation.separator.delimiter', foreground: 'abb2bf' },
    { token: 'punctuation.separator.c,punctuation.separator.cpp', foreground: 'c678dd' },
    {
      token: 'support.type.posix-reserved.c,support.type.posix-reserved.cpp',
      foreground: '56b6c2',
    },
    { token: 'keyword.operator.sizeof.c,keyword.operator.sizeof.cpp', foreground: 'c678dd' },
    { token: 'variable.parameter.function.language.python', foreground: 'd19a66' },
    { token: 'support.type.python', foreground: '56b6c2' },
    { token: 'keyword.operator.logical.python', foreground: 'c678dd' },
    { token: 'variable.parameter.function.python', foreground: 'd19a66' },
    {
      token:
        'punctuation.definition.arguments.begin.python,punctuation.definition.arguments.end.python,punctuation.separator.arguments.python,punctuation.definition.list.begin.python,punctuation.definition.list.end.python',
      foreground: 'abb2bf',
    },
    { token: 'meta.function-call.generic.python', foreground: '61afef' },
    { token: 'constant.character.format.placeholder.other.python', foreground: 'd19a66' },
    { token: 'keyword.operator', foreground: 'abb2bf' },
    { token: 'keyword.operator.assignment.compound', foreground: 'c678dd' },
    {
      token: 'keyword.operator.assignment.compound.js,keyword.operator.assignment.compound.ts',
      foreground: '56b6c2',
    },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'entity.name.namespace', foreground: 'e5c07b' },
    { token: 'variable', foreground: 'e06c75' },
    { token: 'variable.c', foreground: 'abb2bf' },
    { token: 'variable.language', foreground: 'e5c07b' },
    { token: 'token.variable.parameter.java', foreground: 'abb2bf' },
    { token: 'import.storage.java', foreground: 'e5c07b' },
    { token: 'token.package.keyword', foreground: 'c678dd' },
    { token: 'token.package', foreground: 'abb2bf' },
    { token: 'entity.name.function', foreground: '61afef' },
    { token: 'meta.require', foreground: '61afef' },
    { token: 'support.function.any-method', foreground: '61afef' },
    { token: 'variable.function', foreground: '61afef' },
    { token: 'entity.name.type.namespace', foreground: 'e5c07b', fontStyle: 'bold' },
    { token: 'support.class, entity.name.type.class', foreground: 'e5c07b' },
    { token: 'entity.name.class.identifier.namespace.type', foreground: 'e5c07b' },
    { token: 'entity.name.class', foreground: 'e5c07b' },
    { token: 'variable.other.class.js', foreground: 'e5c07b' },
    { token: 'variable.other.class.ts', foreground: 'e5c07b' },
    { token: 'variable.other.class.php', foreground: 'e06c75' },
    { token: 'entity.name.type', foreground: 'e5c07b' },
    { token: 'keyword.control', foreground: 'c678dd' },
    { token: 'control.elements, keyword.operator.less', foreground: 'd19a66' },
    { token: 'keyword.other.special-method', foreground: '61afef' },
    { token: 'storage', foreground: 'c678dd' },
    { token: 'token.storage', foreground: 'c678dd' },
    {
      token:
        'keyword.operator.expression.delete,keyword.operator.expression.in,keyword.operator.expression.of,keyword.operator.expression.instanceof,keyword.operator.new,keyword.operator.expression.typeof,keyword.operator.expression.void',
      foreground: 'c678dd',
    },
    { token: 'token.storage.type.java', foreground: 'e5c07b' },
    { token: 'support.function', foreground: '56b6c2' },
    { token: 'support.type.property-name', foreground: 'abb2bf' },
    {
      token:
        'support.type.property-name.toml, support.type.property-name.table.toml, support.type.property-name.array.toml',
      foreground: 'e06c75',
    },
    { token: 'support.constant.property-value', foreground: 'abb2bf' },
    { token: 'support.constant.font-name', foreground: 'd19a66' },
    { token: 'meta.tag', foreground: 'abb2bf' },
    { token: 'string', foreground: '98c379' },
    { token: 'constant.other.symbol', foreground: '56b6c2' },
    { token: 'constant.numeric', foreground: 'd19a66' },
    { token: 'constant', foreground: 'd19a66' },
    { token: 'punctuation.definition.constant', foreground: 'd19a66' },
    { token: 'entity.name.tag', foreground: 'e06c75' },
    { token: 'entity.other.attribute-name', foreground: 'd19a66' },
    { token: 'entity.other.attribute-name.id', foreground: '61afef' },
    { token: 'entity.other.attribute-name.class.css', foreground: 'd19a66' },
    { token: 'meta.selector', foreground: 'c678dd' },
    { token: 'markup.heading', foreground: 'e06c75', fontStyle: 'bold' },
    {
      token: 'markup.heading punctuation.definition.heading, entity.name.section',
      foreground: '61afef',
    },
    { token: 'keyword.other.unit', foreground: 'e06c75' },
    { token: 'markup.bold,todo.bold', foreground: 'd19a66', fontStyle: 'bold' },
    { token: 'punctuation.definition.bold', foreground: 'e5c07b' },
    { token: 'markup.italic, punctuation.definition.italic,todo.emphasis', foreground: 'c678dd' },
    { token: 'emphasis md', foreground: 'c678dd' },
    { token: 'entity.name.section.markdown', foreground: 'e06c75' },
    { token: 'punctuation.definition.heading.markdown', foreground: 'e06c75' },
    { token: 'punctuation.definition.list.begin.markdown', foreground: 'e5c07b' },
    { token: 'markup.heading.setext', foreground: 'abb2bf' },
    { token: 'punctuation.definition.bold.markdown', foreground: 'd19a66' },
    { token: 'markup.inline.raw.markdown', foreground: '98c379' },
    { token: 'markup.inline.raw.string.markdown', foreground: '98c379' },
    { token: 'punctuation.definition.raw.markdown', foreground: 'e5c07b' },
    { token: 'punctuation.definition.list.markdown', foreground: 'e5c07b' },
    { token: 'punctuation.definition.string.begin.markdown', foreground: 'e06c75' },
    { token: 'punctuation.definition.string.end.markdown', foreground: 'e06c75' },
    { token: 'punctuation.definition.metadata.markdown', foreground: 'e06c75' },
    { token: 'beginning.punctuation.definition.list.markdown', foreground: 'e06c75' },
    { token: 'punctuation.definition.metadata.markdown', foreground: 'e06c75' },
    {
      token: 'markup.underline.link.markdown,markup.underline.link.image.markdown',
      foreground: 'c678dd',
    },
    {
      token: 'string.other.link.title.markdown,string.other.link.description.markdown',
      foreground: '61afef',
    },
    { token: 'markup.raw.monospace.asciidoc', foreground: '98c379' },
    { token: 'punctuation.definition.asciidoc', foreground: 'e5c07b' },
    { token: 'markup.list.asciidoc', foreground: 'e5c07b' },
    { token: 'markup.link.asciidoc,markup.other.url.asciidoc', foreground: 'c678dd' },
    { token: 'string.unquoted.asciidoc,markup.other.url.asciidoc', foreground: '61afef' },
    { token: 'string.regexp', foreground: '56b6c2' },
    { token: 'punctuation.section.embedded, variable.interpolation', foreground: 'e06c75' },
    {
      token: 'punctuation.section.embedded.begin,punctuation.section.embedded.end',
      foreground: 'c678dd',
    },
    { token: 'invalid.illegal', foreground: 'ffffff' },
    { token: 'invalid.illegal.bad-ampersand.html', foreground: 'abb2bf' },
    { token: 'invalid.illegal.unrecognized-tag.html', foreground: 'e06c75' },
    { token: 'invalid.broken', foreground: 'ffffff' },
    { token: 'invalid.deprecated', foreground: 'ffffff' },
    { token: 'invalid.deprecated.entity.other.attribute-name.html', foreground: 'd19a66' },
    { token: 'invalid.unimplemented', foreground: 'ffffff' },
    {
      token: 'source.json meta.structure.dictionary.json > string.quoted.json',
      foreground: 'e06c75',
    },
    {
      token: 'source.json meta.structure.dictionary.json > string.quoted.json > punctuation.string',
      foreground: 'e06c75',
    },
    {
      token:
        'source.json meta.structure.dictionary.json > value.json > string.quoted.json,source.json meta.structure.array.json > value.json > string.quoted.json,source.json meta.structure.dictionary.json > value.json > string.quoted.json > punctuation,source.json meta.structure.array.json > value.json > string.quoted.json > punctuation',
      foreground: '98c379',
    },
    {
      token:
        'source.json meta.structure.dictionary.json > constant.language.json,source.json meta.structure.array.json > constant.language.json',
      foreground: '56b6c2',
    },
    { token: 'support.type.property-name.json', foreground: 'e06c75' },
    { token: 'support.type.property-name.json punctuation', foreground: 'e06c75' },
    {
      token: 'text.html.laravel-blade source.php.embedded.line.html entity.name.tag.laravel-blade',
      foreground: 'c678dd',
    },
    {
      token: 'text.html.laravel-blade source.php.embedded.line.html support.constant.laravel-blade',
      foreground: 'c678dd',
    },
    {
      token:
        'support.other.namespace.use.php,support.other.namespace.use-as.php,entity.other.alias.php,meta.interface.php',
      foreground: 'e5c07b',
    },
    { token: 'keyword.operator.error-control.php', foreground: 'c678dd' },
    { token: 'keyword.operator.type.php', foreground: 'c678dd' },
    { token: 'punctuation.section.array.begin.php', foreground: 'abb2bf' },
    { token: 'punctuation.section.array.end.php', foreground: 'abb2bf' },
    { token: 'invalid.illegal.non-null-typehinted.php', foreground: 'f44747' },
    {
      token:
        'storage.type.php,meta.other.type.phpdoc.php,keyword.other.type.php,keyword.other.array.phpdoc.php',
      foreground: 'e5c07b',
    },
    {
      token: 'meta.function-call.php,meta.function-call.object.php,meta.function-call.static.php',
      foreground: '61afef',
    },
    {
      token:
        'punctuation.definition.parameters.begin.bracket.round.php,punctuation.definition.parameters.end.bracket.round.php,punctuation.separator.delimiter.php,punctuation.section.scope.begin.php,punctuation.section.scope.end.php,punctuation.terminator.expression.php,punctuation.definition.arguments.begin.bracket.round.php,punctuation.definition.arguments.end.bracket.round.php,punctuation.definition.storage-type.begin.bracket.round.php,punctuation.definition.storage-type.end.bracket.round.php,punctuation.definition.array.begin.bracket.round.php,punctuation.definition.array.end.bracket.round.php,punctuation.definition.begin.bracket.round.php,punctuation.definition.end.bracket.round.php,punctuation.definition.begin.bracket.curly.php,punctuation.definition.end.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php,punctuation.definition.section.switch-block.start.bracket.curly.php,punctuation.definition.section.switch-block.begin.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php',
      foreground: 'abb2bf',
    },
    { token: 'support.constant.core.rust', foreground: 'd19a66' },
    {
      token:
        'support.constant.ext.php,support.constant.std.php,support.constant.core.php,support.constant.parser-token.php',
      foreground: 'd19a66',
    },
    { token: 'entity.name.goto-label.php,support.other.php', foreground: '61afef' },
    {
      token:
        'keyword.operator.logical.php,keyword.operator.bitwise.php,keyword.operator.arithmetic.php',
      foreground: '56b6c2',
    },
    { token: 'keyword.operator.regexp.php', foreground: 'c678dd' },
    { token: 'keyword.operator.comparison.php', foreground: '56b6c2' },
    { token: 'keyword.operator.heredoc.php,keyword.operator.nowdoc.php', foreground: 'c678dd' },
    { token: 'meta.function.decorator.python', foreground: '61afef' },
    {
      token: 'support.token.decorator.python,meta.function.decorator.identifier.python',
      foreground: '56b6c2',
    },
    { token: 'function.parameter', foreground: 'abb2bf' },
    { token: 'function.brace', foreground: 'abb2bf' },
    { token: 'function.parameter.ruby, function.parameter.cs', foreground: 'abb2bf' },
    { token: 'constant.language.symbol.ruby', foreground: '56b6c2' },
    { token: 'constant.language.symbol.hashkey.ruby', foreground: '56b6c2' },
    { token: 'rgb-value', foreground: '56b6c2' },
    { token: 'inline-color-decoration rgb-value', foreground: 'd19a66' },
    { token: 'less rgb-value', foreground: 'd19a66' },
    { token: 'selector.sass', foreground: 'e06c75' },
    {
      token:
        'support.type.primitive.ts,support.type.builtin.ts,support.type.primitive.tsx,support.type.builtin.tsx',
      foreground: 'e5c07b',
    },
    { token: 'block.scope.end,block.scope.begin', foreground: 'abb2bf' },
    { token: 'storage.type.cs', foreground: 'e5c07b' },
    { token: 'entity.name.variable.local.cs', foreground: 'e06c75' },
    { token: 'token.info-token', foreground: '61afef' },
    { token: 'token.warn-token', foreground: 'd19a66' },
    { token: 'token.error-token', foreground: 'f44747' },
    { token: 'token.debug-token', foreground: 'c678dd' },
    { token: 'punctuation.definition.template-expression.begin', foreground: 'c678dd' },
    { token: 'punctuation.definition.template-expression.end', foreground: 'c678dd' },
    { token: 'punctuation.section.embedded', foreground: 'c678dd' },
    { token: 'meta.template.expression', foreground: 'abb2bf' },
    { token: 'keyword.operator.module', foreground: 'c678dd' },
    { token: 'support.type.type.flowtype', foreground: '61afef' },
    { token: 'support.type.primitive', foreground: 'e5c07b' },
    { token: 'meta.property.object', foreground: 'e06c75' },
    { token: 'variable.parameter.function.js', foreground: 'e06c75' },
    { token: 'keyword.other.template.begin', foreground: '98c379' },
    { token: 'keyword.other.template.end', foreground: '98c379' },
    { token: 'keyword.other.substitution.begin', foreground: '98c379' },
    { token: 'keyword.other.substitution.end', foreground: '98c379' },
    { token: 'keyword.operator.assignment', foreground: '56b6c2' },
    { token: 'keyword.operator.assignment.go', foreground: 'e5c07b' },
    { token: 'keyword.operator.arithmetic.go', foreground: 'c678dd' },
    { token: 'keyword.operator.address.go', foreground: 'c678dd' },
    { token: 'keyword.operator.arithmetic.c', foreground: 'c678dd' },
    { token: 'keyword.operator.arithmetic.cpp', foreground: 'c678dd' },
    { token: 'entity.name.package.go', foreground: 'e5c07b' },
    { token: 'support.type.prelude.elm', foreground: '56b6c2' },
    { token: 'support.constant.elm', foreground: 'd19a66' },
    { token: 'punctuation.quasi.element', foreground: 'c678dd' },
    { token: 'constant.character.entity', foreground: 'e06c75' },
    { token: 'entity.other.attribute-name.pseudo-element', foreground: '56b6c2' },
    { token: 'entity.other.attribute-name.pseudo-class', foreground: '56b6c2' },
    { token: 'entity.global.clojure', foreground: 'e5c07b' },
    { token: 'meta.symbol.clojure', foreground: 'e06c75' },
    { token: 'constant.keyword.clojure', foreground: '56b6c2' },
    { token: 'meta.arguments.coffee', foreground: 'e06c75' },
    { token: 'variable.parameter.function.coffee', foreground: 'e06c75' },
    { token: 'source.ini', foreground: '98c379' },
    { token: 'meta.scope.prerequisites.makefile', foreground: 'e06c75' },
    { token: 'source.makefile', foreground: 'e5c07b' },
    { token: 'storage.modifier.import.groovy', foreground: 'e5c07b' },
    { token: 'meta.method.groovy', foreground: '61afef' },
    { token: 'meta.definition.variable.name.groovy', foreground: 'e06c75' },
    { token: 'meta.definition.class.inherited.classes.groovy', foreground: '98c379' },
    { token: 'support.variable.semantic.hlsl', foreground: 'e5c07b' },
    { token: 'support.type.texture.hlsl', foreground: 'c678dd' },
    { token: 'support.type.sampler.hlsl', foreground: 'c678dd' },
    { token: 'support.type.object.hlsl', foreground: 'c678dd' },
    { token: 'support.type.object.rw.hlsl', foreground: 'c678dd' },
    { token: 'support.type.fx.hlsl', foreground: 'c678dd' },
    { token: 'support.type.object.hlsl', foreground: 'c678dd' },
    { token: 'text.variable', foreground: 'e06c75' },
    { token: 'text.bracketed', foreground: 'e06c75' },
    { token: 'support.type.swift', foreground: 'e5c07b' },
    { token: 'support.type.vb.asp', foreground: 'e5c07b' },
    { token: 'entity.name.function.xi', foreground: 'e5c07b' },
    { token: 'entity.name.class.xi', foreground: '56b6c2' },
    { token: 'constant.character.character-class.regexp.xi', foreground: 'e06c75' },
    { token: 'constant.regexp.xi', foreground: 'c678dd' },
    { token: 'keyword.control.xi', foreground: '56b6c2' },
    { token: 'invalid.xi', foreground: 'abb2bf' },
    { token: 'beginning.punctuation.definition.quote.markdown.xi', foreground: '98c379' },
    { token: 'beginning.punctuation.definition.list.markdown.xi', foreground: '7f848e' },
    { token: 'constant.character.xi', foreground: '61afef' },
    { token: 'accent.xi', foreground: '61afef' },
    { token: 'wikiword.xi', foreground: 'd19a66' },
    { token: 'constant.other.color.rgb-value.xi', foreground: 'ffffff' },
    { token: 'punctuation.definition.tag.xi', foreground: '5c6370' },
    { token: 'entity.name.label.cs', foreground: 'e5c07b' },
    { token: 'entity.name.scope-resolution.function.call', foreground: 'e5c07b' },
    { token: 'entity.name.scope-resolution.function.definition', foreground: 'e5c07b' },
    { token: 'entity.name.label.cs', foreground: 'e06c75' },
    { token: 'markup.heading.setext.1.markdown', foreground: 'e06c75' },
    { token: 'markup.heading.setext.2.markdown', foreground: 'e06c75' },
    { token: ' meta.brace.square', foreground: 'abb2bf' },
    { token: 'comment, punctuation.definition.comment', foreground: '7f848e' },
    { token: 'markup.quote.markdown', foreground: '5c6370' },
    { token: 'punctuation.definition.block.sequence.item.yaml', foreground: 'abb2bf' },
    { token: 'constant.language.symbol.elixir', foreground: '56b6c2' },
    { token: 'constant.language.symbol.double-quoted.elixir', foreground: '56b6c2' },
    { token: 'entity.name.variable.parameter.cs', foreground: 'e5c07b' },
    { token: 'entity.name.variable.field.cs', foreground: 'e06c75' },
    { token: 'markup.deleted', foreground: 'e06c75' },
    { token: 'markup.inserted', foreground: '98c379' },
    { token: 'markup.underline', fontStyle: 'underline' },
    { token: 'punctuation.section.embedded.begin.php', foreground: 'BE5046' },
    { token: 'punctuation.section.embedded.end.php', foreground: 'BE5046' },
    { token: 'support.other.namespace.php', foreground: 'abb2bf' },
    { token: 'variable.parameter.function.latex', foreground: 'e06c75' },
    { token: 'variable.other.object', foreground: 'e5c07b' },
    { token: 'variable.other.constant.property', foreground: 'e06c75' },
    { token: 'entity.other.inherited-class', foreground: 'e5c07b' },
    { token: 'variable.other.readwrite.c', foreground: 'e06c75' },
    {
      token:
        'entity.name.variable.parameter.php,punctuation.separator.colon.php,constant.other.php',
      foreground: 'abb2bf',
    },
    { token: 'constant.numeric.decimal.asm.x86_64', foreground: 'c678dd' },
    { token: 'support.other.parenthesis.regexp', foreground: 'd19a66' },
    { token: 'constant.character.escape', foreground: '56b6c2' },
    { token: 'string.regexp', foreground: 'e06c75' },
    { token: 'log.info', foreground: '98c379' },
    { token: 'log.warning', foreground: 'e5c07b' },
    { token: 'log.error', foreground: 'e06c75' },
    { token: 'keyword.operator.expression.is', foreground: 'c678dd' },
    { token: 'entity.name.label', foreground: 'e06c75' },
    { token: 'support.class.math.block.environment.latex', foreground: '61afef' },
    { token: 'constant.other.general.math.tex', foreground: '61afef' },
    { token: 'constant.character.math.tex', foreground: '98c379' },
    { token: 'markup.bold', fontStyle: 'bold' },
    { token: 'entity.name.section', fontStyle: 'bold' },
    { token: 'keyword.other.important', fontStyle: 'bold' },
    { token: 'entity.name.function', fontStyle: 'bold' },
    { token: 'meta.require', fontStyle: 'bold' },
    { token: 'support.function.any-method', fontStyle: 'bold' },
    { token: 'variable.function', fontStyle: 'bold' },
    { token: 'markup.bold.markdown', fontStyle: 'bold' },
  ],
  colors: {},
  tokenColors: [],
}

export const oneLightProFlatTheme: MonacoThemeData = {
  base: 'vs',
  inherit: false,
  rules: [
    { token: 'meta.embedded', foreground: '383a42' },
    {
      token:
        'punctuation.definition.delayed.unison,punctuation.definition.list.begin.unison,punctuation.definition.list.end.unison,punctuation.definition.ability.begin.unison,punctuation.definition.ability.end.unison,punctuation.operator.assignment.as.unison,punctuation.separator.pipe.unison,punctuation.separator.delimiter.unison,punctuation.definition.hash.unison',
      foreground: 'e45649',
    },
    { token: 'variable.other.generic-type.haskell', foreground: 'a626a4' },
    { token: 'storage.type.haskell', foreground: '986801' },
    { token: 'support.variable.magic.python', foreground: 'e45649' },
    {
      token:
        'punctuation.separator.period.python,punctuation.separator.element.python,punctuation.parenthesis.begin.python,punctuation.parenthesis.end.python',
      foreground: '383a42',
    },
    { token: 'variable.parameter.function.language.special.self.python', foreground: '986801' },
    { token: 'variable.parameter.function.language.special.cls.python', foreground: '986801' },
    { token: 'storage.modifier.lifetime.rust', foreground: '383a42' },
    { token: 'support.function.std.rust', foreground: '4078f2' },
    { token: 'entity.name.lifetime.rust', foreground: '986801' },
    { token: 'variable.language.rust', foreground: 'e45649' },
    { token: 'support.constant.edge', foreground: 'a626a4' },
    { token: 'constant.other.character-class.regexp', foreground: 'e45649' },
    { token: 'keyword.operator.word', foreground: 'a626a4' },
    { token: 'keyword.operator.quantifier.regexp', foreground: '986801' },
    { token: 'variable.parameter.function', foreground: '383a42' },
    { token: 'comment markup.link', foreground: '9d9d9f' },
    { token: 'markup.changed.diff', foreground: '986801' },
    {
      token:
        'meta.diff.header.from-file,meta.diff.header.to-file,punctuation.definition.from-file.diff,punctuation.definition.to-file.diff',
      foreground: '4078f2',
    },
    { token: 'markup.inserted.diff', foreground: '50a14f' },
    { token: 'markup.deleted.diff', foreground: 'e45649' },
    { token: 'meta.function.c,meta.function.cpp', foreground: 'e45649' },
    {
      token:
        'punctuation.section.block.begin.bracket.curly.cpp,punctuation.section.block.end.bracket.curly.cpp,punctuation.terminator.statement.c,punctuation.section.block.begin.bracket.curly.c,punctuation.section.block.end.bracket.curly.c,punctuation.section.parens.begin.bracket.round.c,punctuation.section.parens.end.bracket.round.c,punctuation.section.parameters.begin.bracket.round.c,punctuation.section.parameters.end.bracket.round.c',
      foreground: '383a42',
    },
    { token: 'punctuation.separator.key-value', foreground: '383a42' },
    { token: 'keyword.operator.expression.import', foreground: '4078f2' },
    { token: 'support.constant.math', foreground: '986801' },
    { token: 'support.constant.property.math', foreground: '986801' },
    { token: 'variable.other.constant', foreground: '986801' },
    { token: 'storage.type.annotation.java', foreground: '986801' },
    { token: 'storage.type.object.array.java', foreground: '986801' },
    { token: 'source.java', foreground: 'e45649' },
    {
      token:
        'punctuation.section.block.begin.java,punctuation.section.block.end.java,punctuation.definition.method-parameters.begin.java,punctuation.definition.method-parameters.end.java,meta.method.identifier.java,punctuation.section.method.begin.java,punctuation.section.method.end.java,punctuation.terminator.java,punctuation.section.class.begin.java,punctuation.section.class.end.java,punctuation.section.inner-class.begin.java,punctuation.section.inner-class.end.java,meta.method-call.java,punctuation.section.class.begin.bracket.curly.java,punctuation.section.class.end.bracket.curly.java,punctuation.section.method.begin.bracket.curly.java,punctuation.section.method.end.bracket.curly.java,punctuation.separator.period.java,punctuation.bracket.angle.java,punctuation.definition.annotation.java,meta.method.body.java',
      foreground: '383a42',
    },
    { token: 'meta.method.java', foreground: '4078f2' },
    {
      token: 'storage.modifier.import.java,storage.type.java,storage.type.generic.java',
      foreground: '986801',
    },
    { token: 'keyword.operator.instanceof.java', foreground: 'a626a4' },
    { token: 'meta.definition.variable.name.java', foreground: 'e45649' },
    { token: 'keyword.operator.logical', foreground: '0184bc' },
    { token: 'keyword.operator.bitwise', foreground: '0184bc' },
    { token: 'keyword.operator.channel', foreground: '0184bc' },
    {
      token: 'support.constant.property-value.scss,support.constant.property-value.css',
      foreground: '986801',
    },
    {
      token: 'keyword.operator.css,keyword.operator.scss,keyword.operator.less',
      foreground: '0184bc',
    },
    {
      token:
        'support.constant.color.w3c-standard-color-name.css,support.constant.color.w3c-standard-color-name.scss',
      foreground: '986801',
    },
    { token: 'punctuation.separator.list.comma.css', foreground: '383a42' },
    { token: 'support.constant.color.w3c-standard-color-name.css', foreground: '986801' },
    { token: 'support.type.vendored.property-name.css', foreground: '0184bc' },
    {
      token: 'support.module.node,support.type.object.module,support.module.node',
      foreground: '986801',
    },
    { token: 'entity.name.type.module', foreground: '986801' },
    {
      token:
        'variable.other.readwrite,meta.object-literal.key,support.variable.property,support.variable.object.process,support.variable.object.node',
      foreground: 'e45649',
    },
    { token: 'support.constant.json', foreground: '986801' },
    { token: 'keyword.operator.expression.instanceof', foreground: 'a626a4' },
    { token: 'keyword.operator.new', foreground: 'a626a4' },
    { token: 'keyword.operator.ternary', foreground: 'a626a4' },
    { token: 'keyword.operator.optional', foreground: 'a626a4' },
    { token: 'keyword.operator.expression.keyof', foreground: 'a626a4' },
    { token: 'support.type.object.console', foreground: 'e45649' },
    { token: 'support.variable.property.process', foreground: '986801' },
    { token: 'entity.name.function,support.function.console', foreground: '4078f2' },
    { token: 'keyword.operator.misc.rust', foreground: '383a42' },
    { token: 'keyword.operator.sigil.rust', foreground: 'a626a4' },
    { token: 'keyword.operator.delete', foreground: 'a626a4' },
    { token: 'support.type.object.dom', foreground: '0184bc' },
    { token: 'support.variable.dom,support.variable.property.dom', foreground: 'e45649' },
    {
      token:
        'keyword.operator.arithmetic,keyword.operator.comparison,keyword.operator.decrement,keyword.operator.increment,keyword.operator.relational',
      foreground: '0184bc',
    },
    {
      token:
        'keyword.operator.assignment.c,keyword.operator.comparison.c,keyword.operator.c,keyword.operator.increment.c,keyword.operator.decrement.c,keyword.operator.bitwise.shift.c,keyword.operator.assignment.cpp,keyword.operator.comparison.cpp,keyword.operator.cpp,keyword.operator.increment.cpp,keyword.operator.decrement.cpp,keyword.operator.bitwise.shift.cpp',
      foreground: 'a626a4',
    },
    { token: 'punctuation.separator.delimiter', foreground: '383a42' },
    { token: 'punctuation.separator.c,punctuation.separator.cpp', foreground: 'a626a4' },
    {
      token: 'support.type.posix-reserved.c,support.type.posix-reserved.cpp',
      foreground: '0184bc',
    },
    { token: 'keyword.operator.sizeof.c,keyword.operator.sizeof.cpp', foreground: 'a626a4' },
    { token: 'variable.parameter.function.language.python', foreground: '986801' },
    { token: 'support.type.python', foreground: '0184bc' },
    { token: 'keyword.operator.logical.python', foreground: 'a626a4' },
    { token: 'variable.parameter.function.python', foreground: '986801' },
    {
      token:
        'punctuation.definition.arguments.begin.python,punctuation.definition.arguments.end.python,punctuation.separator.arguments.python,punctuation.definition.list.begin.python,punctuation.definition.list.end.python',
      foreground: '383a42',
    },
    { token: 'meta.function-call.generic.python', foreground: '4078f2' },
    { token: 'constant.character.format.placeholder.other.python', foreground: '986801' },
    { token: 'keyword.operator', foreground: '383a42' },
    { token: 'keyword.operator.assignment.compound', foreground: 'a626a4' },
    {
      token: 'keyword.operator.assignment.compound.js,keyword.operator.assignment.compound.ts',
      foreground: '0184bc',
    },
    { token: 'keyword', foreground: 'a626a4' },
    { token: 'entity.name.namespace', foreground: '986801' },
    { token: 'variable', foreground: 'e45649' },
    { token: 'variable.c', foreground: '383a42' },
    { token: 'variable.language', foreground: '986801' },
    { token: 'token.variable.parameter.java', foreground: '383a42' },
    { token: 'import.storage.java', foreground: '986801' },
    { token: 'token.package.keyword', foreground: 'a626a4' },
    { token: 'token.package', foreground: '383a42' },
    { token: 'entity.name.function', foreground: '4078f2' },
    { token: 'meta.require', foreground: '4078f2' },
    { token: 'support.function.any-method', foreground: '4078f2' },
    { token: 'variable.function', foreground: '4078f2' },
    { token: 'entity.name.type.namespace', foreground: '986801', fontStyle: 'bold' },
    { token: 'support.class, entity.name.type.class', foreground: '986801' },
    { token: 'entity.name.class.identifier.namespace.type', foreground: '986801' },
    { token: 'entity.name.class', foreground: '986801' },
    { token: 'variable.other.class.js', foreground: '986801' },
    { token: 'variable.other.class.ts', foreground: '986801' },
    { token: 'variable.other.class.php', foreground: 'e45649' },
    { token: 'entity.name.type', foreground: '986801' },
    { token: 'keyword.control', foreground: 'a626a4' },
    { token: 'control.elements, keyword.operator.less', foreground: '986801' },
    { token: 'keyword.other.special-method', foreground: '4078f2' },
    { token: 'storage', foreground: 'a626a4' },
    { token: 'token.storage', foreground: 'a626a4' },
    {
      token:
        'keyword.operator.expression.delete,keyword.operator.expression.in,keyword.operator.expression.of,keyword.operator.expression.instanceof,keyword.operator.new,keyword.operator.expression.typeof,keyword.operator.expression.void',
      foreground: 'a626a4',
    },
    { token: 'token.storage.type.java', foreground: '986801' },
    { token: 'support.function', foreground: '0184bc' },
    { token: 'support.type.property-name', foreground: '383a42' },
    {
      token:
        'support.type.property-name.toml, support.type.property-name.table.toml, support.type.property-name.array.toml',
      foreground: 'e45649',
    },
    { token: 'support.constant.property-value', foreground: '383a42' },
    { token: 'support.constant.font-name', foreground: '986801' },
    { token: 'meta.tag', foreground: '383a42' },
    { token: 'string', foreground: '50a14f' },
    { token: 'constant.other.symbol', foreground: '0184bc' },
    { token: 'constant.numeric', foreground: '986801' },
    { token: 'constant', foreground: '986801' },
    { token: 'punctuation.definition.constant', foreground: '986801' },
    { token: 'entity.name.tag', foreground: 'e45649' },
    { token: 'entity.other.attribute-name', foreground: '986801' },
    { token: 'entity.other.attribute-name.id', foreground: '4078f2' },
    { token: 'entity.other.attribute-name.class.css', foreground: '986801' },
    { token: 'meta.selector', foreground: 'a626a4' },
    { token: 'markup.heading', foreground: 'e45649', fontStyle: 'bold' },
    {
      token: 'markup.heading punctuation.definition.heading, entity.name.section',
      foreground: '4078f2',
    },
    { token: 'keyword.other.unit', foreground: 'e45649' },
    { token: 'markup.bold,todo.bold', foreground: '986801', fontStyle: 'bold' },
    { token: 'punctuation.definition.bold', foreground: '986801' },
    { token: 'markup.italic, punctuation.definition.italic,todo.emphasis', foreground: 'a626a4' },
    { token: 'emphasis md', foreground: 'a626a4' },
    { token: 'entity.name.section.markdown', foreground: 'e45649' },
    { token: 'punctuation.definition.heading.markdown', foreground: 'e45649' },
    { token: 'punctuation.definition.list.begin.markdown', foreground: '986801' },
    { token: 'markup.heading.setext', foreground: '383a42' },
    { token: 'punctuation.definition.bold.markdown', foreground: '986801' },
    { token: 'markup.inline.raw.markdown', foreground: '50a14f' },
    { token: 'markup.inline.raw.string.markdown', foreground: '50a14f' },
    { token: 'punctuation.definition.raw.markdown', foreground: '986801' },
    { token: 'punctuation.definition.list.markdown', foreground: '986801' },
    { token: 'punctuation.definition.string.begin.markdown', foreground: 'e45649' },
    { token: 'punctuation.definition.string.end.markdown', foreground: 'e45649' },
    { token: 'punctuation.definition.metadata.markdown', foreground: 'e45649' },
    { token: 'beginning.punctuation.definition.list.markdown', foreground: 'e45649' },
    { token: 'punctuation.definition.metadata.markdown', foreground: 'e45649' },
    {
      token: 'markup.underline.link.markdown,markup.underline.link.image.markdown',
      foreground: 'a626a4',
    },
    {
      token: 'string.other.link.title.markdown,string.other.link.description.markdown',
      foreground: '4078f2',
    },
    { token: 'markup.raw.monospace.asciidoc', foreground: '50a14f' },
    { token: 'punctuation.definition.asciidoc', foreground: '986801' },
    { token: 'markup.list.asciidoc', foreground: '986801' },
    { token: 'markup.link.asciidoc,markup.other.url.asciidoc', foreground: 'a626a4' },
    { token: 'string.unquoted.asciidoc,markup.other.url.asciidoc', foreground: '4078f2' },
    { token: 'string.regexp', foreground: '0184bc' },
    { token: 'punctuation.section.embedded, variable.interpolation', foreground: 'e45649' },
    {
      token: 'punctuation.section.embedded.begin,punctuation.section.embedded.end',
      foreground: 'a626a4',
    },
    { token: 'invalid.illegal', foreground: '383a42' },
    { token: 'invalid.illegal.bad-ampersand.html', foreground: '383a42' },
    { token: 'invalid.illegal.unrecognized-tag.html', foreground: 'e45649' },
    { token: 'invalid.broken', foreground: '383a42' },
    { token: 'invalid.deprecated', foreground: '383a42' },
    { token: 'invalid.deprecated.entity.other.attribute-name.html', foreground: '986801' },
    { token: 'invalid.unimplemented', foreground: '383a42' },
    {
      token: 'source.json meta.structure.dictionary.json > string.quoted.json',
      foreground: 'e45649',
    },
    {
      token: 'source.json meta.structure.dictionary.json > string.quoted.json > punctuation.string',
      foreground: 'e45649',
    },
    {
      token:
        'source.json meta.structure.dictionary.json > value.json > string.quoted.json,source.json meta.structure.array.json > value.json > string.quoted.json,source.json meta.structure.dictionary.json > value.json > string.quoted.json > punctuation,source.json meta.structure.array.json > value.json > string.quoted.json > punctuation',
      foreground: '50a14f',
    },
    {
      token:
        'source.json meta.structure.dictionary.json > constant.language.json,source.json meta.structure.array.json > constant.language.json',
      foreground: '0184bc',
    },
    { token: 'support.type.property-name.json', foreground: 'e45649' },
    { token: 'support.type.property-name.json punctuation', foreground: 'e45649' },
    {
      token: 'text.html.laravel-blade source.php.embedded.line.html entity.name.tag.laravel-blade',
      foreground: 'a626a4',
    },
    {
      token: 'text.html.laravel-blade source.php.embedded.line.html support.constant.laravel-blade',
      foreground: 'a626a4',
    },
    {
      token:
        'support.other.namespace.use.php,support.other.namespace.use-as.php,entity.other.alias.php,meta.interface.php',
      foreground: '986801',
    },
    { token: 'keyword.operator.error-control.php', foreground: 'a626a4' },
    { token: 'keyword.operator.type.php', foreground: 'a626a4' },
    { token: 'punctuation.section.array.begin.php', foreground: '383a42' },
    { token: 'punctuation.section.array.end.php', foreground: '383a42' },
    { token: 'invalid.illegal.non-null-typehinted.php', foreground: 'f44747' },
    {
      token:
        'storage.type.php,meta.other.type.phpdoc.php,keyword.other.type.php,keyword.other.array.phpdoc.php',
      foreground: '986801',
    },
    {
      token: 'meta.function-call.php,meta.function-call.object.php,meta.function-call.static.php',
      foreground: '4078f2',
    },
    {
      token:
        'punctuation.definition.parameters.begin.bracket.round.php,punctuation.definition.parameters.end.bracket.round.php,punctuation.separator.delimiter.php,punctuation.section.scope.begin.php,punctuation.section.scope.end.php,punctuation.terminator.expression.php,punctuation.definition.arguments.begin.bracket.round.php,punctuation.definition.arguments.end.bracket.round.php,punctuation.definition.storage-type.begin.bracket.round.php,punctuation.definition.storage-type.end.bracket.round.php,punctuation.definition.array.begin.bracket.round.php,punctuation.definition.array.end.bracket.round.php,punctuation.definition.begin.bracket.round.php,punctuation.definition.end.bracket.round.php,punctuation.definition.begin.bracket.curly.php,punctuation.definition.end.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php,punctuation.definition.section.switch-block.start.bracket.curly.php,punctuation.definition.section.switch-block.begin.bracket.curly.php,punctuation.definition.section.switch-block.end.bracket.curly.php',
      foreground: '383a42',
    },
    { token: 'support.constant.core.rust', foreground: '986801' },
    {
      token:
        'support.constant.ext.php,support.constant.std.php,support.constant.core.php,support.constant.parser-token.php',
      foreground: '986801',
    },
    { token: 'entity.name.goto-label.php,support.other.php', foreground: '4078f2' },
    {
      token:
        'keyword.operator.logical.php,keyword.operator.bitwise.php,keyword.operator.arithmetic.php',
      foreground: '0184bc',
    },
    { token: 'keyword.operator.regexp.php', foreground: 'a626a4' },
    { token: 'keyword.operator.comparison.php', foreground: '0184bc' },
    { token: 'keyword.operator.heredoc.php,keyword.operator.nowdoc.php', foreground: 'a626a4' },
    { token: 'meta.function.decorator.python', foreground: '4078f2' },
    {
      token: 'support.token.decorator.python,meta.function.decorator.identifier.python',
      foreground: '0184bc',
    },
    { token: 'function.parameter', foreground: '383a42' },
    { token: 'function.brace', foreground: '383a42' },
    { token: 'function.parameter.ruby, function.parameter.cs', foreground: '383a42' },
    { token: 'constant.language.symbol.ruby', foreground: '0184bc' },
    { token: 'constant.language.symbol.hashkey.ruby', foreground: '0184bc' },
    { token: 'rgb-value', foreground: '0184bc' },
    { token: 'inline-color-decoration rgb-value', foreground: '986801' },
    { token: 'less rgb-value', foreground: '986801' },
    { token: 'selector.sass', foreground: 'e45649' },
    {
      token:
        'support.type.primitive.ts,support.type.builtin.ts,support.type.primitive.tsx,support.type.builtin.tsx',
      foreground: '986801',
    },
    { token: 'block.scope.end,block.scope.begin', foreground: '383a42' },
    { token: 'storage.type.cs', foreground: '986801' },
    { token: 'entity.name.variable.local.cs', foreground: 'e45649' },
    { token: 'token.info-token', foreground: '4078f2' },
    { token: 'token.warn-token', foreground: '986801' },
    { token: 'token.error-token', foreground: 'f44747' },
    { token: 'token.debug-token', foreground: 'a626a4' },
    { token: 'punctuation.definition.template-expression.begin', foreground: 'a626a4' },
    { token: 'punctuation.definition.template-expression.end', foreground: 'a626a4' },
    { token: 'punctuation.section.embedded', foreground: 'a626a4' },
    { token: 'meta.template.expression', foreground: '383a42' },
    { token: 'keyword.operator.module', foreground: 'a626a4' },
    { token: 'support.type.type.flowtype', foreground: '4078f2' },
    { token: 'support.type.primitive', foreground: '986801' },
    { token: 'meta.property.object', foreground: 'e45649' },
    { token: 'variable.parameter.function.js', foreground: 'e45649' },
    { token: 'keyword.other.template.begin', foreground: '50a14f' },
    { token: 'keyword.other.template.end', foreground: '50a14f' },
    { token: 'keyword.other.substitution.begin', foreground: '50a14f' },
    { token: 'keyword.other.substitution.end', foreground: '50a14f' },
    { token: 'keyword.operator.assignment', foreground: '0184bc' },
    { token: 'keyword.operator.assignment.go', foreground: '986801' },
    { token: 'keyword.operator.arithmetic.go', foreground: 'a626a4' },
    { token: 'keyword.operator.address.go', foreground: 'a626a4' },
    { token: 'keyword.operator.arithmetic.c', foreground: 'a626a4' },
    { token: 'keyword.operator.arithmetic.cpp', foreground: 'a626a4' },
    { token: 'entity.name.package.go', foreground: '986801' },
    { token: 'support.type.prelude.elm', foreground: '0184bc' },
    { token: 'support.constant.elm', foreground: '986801' },
    { token: 'punctuation.quasi.element', foreground: 'a626a4' },
    { token: 'constant.character.entity', foreground: 'e45649' },
    { token: 'entity.other.attribute-name.pseudo-element', foreground: '0184bc' },
    { token: 'entity.other.attribute-name.pseudo-class', foreground: '0184bc' },
    { token: 'entity.global.clojure', foreground: '986801' },
    { token: 'meta.symbol.clojure', foreground: 'e45649' },
    { token: 'constant.keyword.clojure', foreground: '0184bc' },
    { token: 'meta.arguments.coffee', foreground: 'e45649' },
    { token: 'variable.parameter.function.coffee', foreground: 'e45649' },
    { token: 'source.ini', foreground: '50a14f' },
    { token: 'meta.scope.prerequisites.makefile', foreground: 'e45649' },
    { token: 'source.makefile', foreground: '986801' },
    { token: 'storage.modifier.import.groovy', foreground: '986801' },
    { token: 'meta.method.groovy', foreground: '4078f2' },
    { token: 'meta.definition.variable.name.groovy', foreground: 'e45649' },
    { token: 'meta.definition.class.inherited.classes.groovy', foreground: '50a14f' },
    { token: 'support.variable.semantic.hlsl', foreground: '986801' },
    { token: 'support.type.texture.hlsl', foreground: 'a626a4' },
    { token: 'support.type.sampler.hlsl', foreground: 'a626a4' },
    { token: 'support.type.object.hlsl', foreground: 'a626a4' },
    { token: 'support.type.object.rw.hlsl', foreground: 'a626a4' },
    { token: 'support.type.fx.hlsl', foreground: 'a626a4' },
    { token: 'support.type.object.hlsl', foreground: 'a626a4' },
    { token: 'text.variable', foreground: 'e45649' },
    { token: 'text.bracketed', foreground: 'e45649' },
    { token: 'support.type.swift', foreground: '986801' },
    { token: 'support.type.vb.asp', foreground: '986801' },
    { token: 'entity.name.function.xi', foreground: '986801' },
    { token: 'entity.name.class.xi', foreground: '0184bc' },
    { token: 'constant.character.character-class.regexp.xi', foreground: 'e45649' },
    { token: 'constant.regexp.xi', foreground: 'a626a4' },
    { token: 'keyword.control.xi', foreground: '0184bc' },
    { token: 'invalid.xi', foreground: '383a42' },
    { token: 'beginning.punctuation.definition.quote.markdown.xi', foreground: '50a14f' },
    { token: 'beginning.punctuation.definition.list.markdown.xi', foreground: '7f848e' },
    { token: 'constant.character.xi', foreground: '4078f2' },
    { token: 'accent.xi', foreground: '4078f2' },
    { token: 'wikiword.xi', foreground: '986801' },
    { token: 'constant.other.color.rgb-value.xi', foreground: '383a42' },
    { token: 'punctuation.definition.tag.xi', foreground: '9d9d9f' },
    { token: 'entity.name.label.cs', foreground: '986801' },
    { token: 'entity.name.scope-resolution.function.call', foreground: '986801' },
    { token: 'entity.name.scope-resolution.function.definition', foreground: '986801' },
    { token: 'entity.name.label.cs', foreground: 'e45649' },
    { token: 'markup.heading.setext.1.markdown', foreground: 'e45649' },
    { token: 'markup.heading.setext.2.markdown', foreground: 'e45649' },
    { token: ' meta.brace.square', foreground: '383a42' },
    { token: 'comment, punctuation.definition.comment', foreground: '7f848e' },
    { token: 'markup.quote.markdown', foreground: '9d9d9f' },
    { token: 'punctuation.definition.block.sequence.item.yaml', foreground: '383a42' },
    { token: 'constant.language.symbol.elixir', foreground: '0184bc' },
    { token: 'constant.language.symbol.double-quoted.elixir', foreground: '0184bc' },
    { token: 'entity.name.variable.parameter.cs', foreground: '986801' },
    { token: 'entity.name.variable.field.cs', foreground: 'e45649' },
    { token: 'markup.deleted', foreground: 'e45649' },
    { token: 'markup.inserted', foreground: '50a14f' },
    { token: 'markup.underline', fontStyle: 'underline' },
    { token: 'punctuation.section.embedded.begin.php', foreground: 'ca1243' },
    { token: 'punctuation.section.embedded.end.php', foreground: 'ca1243' },
    { token: 'support.other.namespace.php', foreground: '383a42' },
    { token: 'variable.parameter.function.latex', foreground: 'e45649' },
    { token: 'variable.other.object', foreground: '986801' },
    { token: 'variable.other.constant.property', foreground: 'e45649' },
    { token: 'entity.other.inherited-class', foreground: '986801' },
    { token: 'variable.other.readwrite.c', foreground: 'e45649' },
    {
      token:
        'entity.name.variable.parameter.php,punctuation.separator.colon.php,constant.other.php',
      foreground: '383a42',
    },
    { token: 'constant.numeric.decimal.asm.x86_64', foreground: 'a626a4' },
    { token: 'support.other.parenthesis.regexp', foreground: '986801' },
    { token: 'constant.character.escape', foreground: '0184bc' },
    { token: 'string.regexp', foreground: 'e45649' },
    { token: 'log.info', foreground: '50a14f' },
    { token: 'log.warning', foreground: '986801' },
    { token: 'log.error', foreground: 'e45649' },
    { token: 'keyword.operator.expression.is', foreground: 'a626a4' },
    { token: 'entity.name.label', foreground: 'e45649' },
    { token: 'support.class.math.block.environment.latex', foreground: '4078f2' },
    { token: 'constant.other.general.math.tex', foreground: '4078f2' },
    { token: 'constant.character.math.tex', foreground: '50a14f' },
    { token: 'markup.bold', fontStyle: 'bold' },
    { token: 'entity.name.section', fontStyle: 'bold' },
    { token: 'keyword.other.important', fontStyle: 'bold' },
    { token: 'entity.name.function', fontStyle: 'bold' },
    { token: 'meta.require', fontStyle: 'bold' },
    { token: 'support.function.any-method', fontStyle: 'bold' },
    { token: 'variable.function', fontStyle: 'bold' },
    { token: 'markup.bold.markdown', fontStyle: 'bold' },
  ],
  colors: {},
  tokenColors: [],
}
