// One Dark Pro Flat — dark + One Light variant
// Uses actual Monaco tokenizer token names (NOT VS Code TextMate scopes)
// Monaco TS tokens: keyword, string, number, comment, type.identifier, identifier, regexp, delimiter...
// Chrome colors injected at runtime by applyShadcnTheme() from shadcn CSS vars

import type { editor } from 'monaco-editor'

type MonacoThemeData = editor.IStandaloneThemeData

export const oneDarkProFlatTheme: MonacoThemeData = {
  base: 'vs-dark',
  inherit: true,
  rules: [
    { token: '', foreground: 'abb2bf' },
    { token: 'comment', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: '5c6370', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'c678dd' },
    { token: 'keyword.other', foreground: 'c678dd' },
    { token: 'string', foreground: '98c379' },
    { token: 'string.escape', foreground: '56b6c2' },
    { token: 'string.escape.invalid', foreground: 'e06c75' },
    { token: 'string.invalid', foreground: 'e06c75' },
    { token: 'number', foreground: 'd19a66' },
    { token: 'number.float', foreground: 'd19a66' },
    { token: 'number.hex', foreground: 'd19a66' },
    { token: 'number.binary', foreground: 'd19a66' },
    { token: 'number.octal', foreground: 'd19a66' },
    { token: 'type.identifier', foreground: 'e5c07b' },
    { token: 'identifier', foreground: 'abb2bf' },
    { token: 'regexp', foreground: '56b6c2' },
    { token: 'regexp.escape', foreground: '98c379' },
    { token: 'regexp.escape.control', foreground: 'c678dd' },
    { token: 'regexp.invalid', foreground: 'e06c75' },
    { token: 'delimiter', foreground: 'abb2bf' },
    { token: 'delimiter.bracket', foreground: 'abb2bf' },
    { token: 'invalid', foreground: 'e06c75' },
    { token: 'tag', foreground: 'e06c75' },
    { token: 'tag.id', foreground: 'e06c75' },
    { token: 'tag.class', foreground: 'd19a66' },
    { token: 'attribute.name', foreground: 'd19a66' },
    { token: 'attribute.value', foreground: '98c379' },
    { token: 'attribute.name.css', foreground: '56b6c2' },
    { token: 'attribute.value.css', foreground: '98c379' },
    { token: 'attribute.value.number.css', foreground: 'd19a66' },
    { token: 'attribute.value.unit.css', foreground: 'd19a66' },
    { token: 'attribute.value.hex.css', foreground: 'd19a66' },
    { token: 'string.key.json', foreground: 'e06c75' },
    { token: 'string.value.json', foreground: '98c379' },
    { token: 'emphasis', fontStyle: 'italic' },
    { token: 'strong', fontStyle: 'bold' },
  ],
  colors: {},
  tokenColors: [],
}

export const oneLightProFlatTheme: MonacoThemeData = {
  base: 'vs',
  inherit: true,
  rules: [
    { token: '', foreground: '383a42' },
    { token: 'comment', foreground: 'a0a1a7', fontStyle: 'italic' },
    { token: 'comment.doc', foreground: 'a0a1a7', fontStyle: 'italic' },
    { token: 'keyword', foreground: 'a626a4' },
    { token: 'keyword.other', foreground: 'a626a4' },
    { token: 'string', foreground: '50a14f' },
    { token: 'string.escape', foreground: '0184bc' },
    { token: 'string.escape.invalid', foreground: 'e45649' },
    { token: 'string.invalid', foreground: 'e45649' },
    { token: 'number', foreground: '986801' },
    { token: 'number.float', foreground: '986801' },
    { token: 'number.hex', foreground: '986801' },
    { token: 'number.binary', foreground: '986801' },
    { token: 'number.octal', foreground: '986801' },
    { token: 'type.identifier', foreground: 'c18401' },
    { token: 'identifier', foreground: '383a42' },
    { token: 'regexp', foreground: '0184bc' },
    { token: 'regexp.escape', foreground: '50a14f' },
    { token: 'regexp.escape.control', foreground: 'a626a4' },
    { token: 'regexp.invalid', foreground: 'e45649' },
    { token: 'delimiter', foreground: '383a42' },
    { token: 'delimiter.bracket', foreground: '383a42' },
    { token: 'invalid', foreground: 'e45649' },
    { token: 'tag', foreground: 'e45649' },
    { token: 'tag.id', foreground: 'e45649' },
    { token: 'tag.class', foreground: '986801' },
    { token: 'attribute.name', foreground: '986801' },
    { token: 'attribute.value', foreground: '50a14f' },
    { token: 'attribute.name.css', foreground: '0184bc' },
    { token: 'attribute.value.css', foreground: '50a14f' },
    { token: 'attribute.value.number.css', foreground: '986801' },
    { token: 'attribute.value.unit.css', foreground: '986801' },
    { token: 'attribute.value.hex.css', foreground: '986801' },
    { token: 'string.key.json', foreground: 'e45649' },
    { token: 'string.value.json', foreground: '50a14f' },
    { token: 'emphasis', fontStyle: 'italic' },
    { token: 'strong', fontStyle: 'bold' },
  ],
  colors: {},
  tokenColors: [],
}
