// @ts-nocheck
// Autogenerated — only ui components
import { lazy } from "react"

export const Index: Record<string, Record<string, any>> = {
  "new-york-v4": {
    "accordion": {
      name: "accordion",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/accordion")),
    },
    "alert": {
      name: "alert",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/alert")),
    },
    "alert-dialog": {
      name: "alert-dialog",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/alert-dialog")),
    },
    "aspect-ratio": {
      name: "aspect-ratio",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/aspect-ratio")),
    },
    "avatar": {
      name: "avatar",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/avatar")),
    },
    "badge": {
      name: "badge",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/badge")),
    },
    "breadcrumb": {
      name: "breadcrumb",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/breadcrumb")),
    },
    "button": {
      name: "button",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/button")),
    },
    "button-group": {
      name: "button-group",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/button-group")),
    },
    "calendar": {
      name: "calendar",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/calendar")),
    },
    "card": {
      name: "card",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/card")),
    },
    "carousel": {
      name: "carousel",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/carousel")),
    },
    "chart": {
      name: "chart",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/chart")),
    },
    "checkbox": {
      name: "checkbox",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/checkbox")),
    },
    "collapsible": {
      name: "collapsible",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/collapsible")),
    },
    "combobox": {
      name: "combobox",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/combobox")),
    },
    "command": {
      name: "command",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/command")),
    },
    "context-menu": {
      name: "context-menu",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/context-menu")),
    },
    "dialog": {
      name: "dialog",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/dialog")),
    },
    "direction": {
      name: "direction",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/direction")),
    },
    "drawer": {
      name: "drawer",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/drawer")),
    },
    "dropdown-menu": {
      name: "dropdown-menu",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/dropdown-menu")),
    },
    "empty": {
      name: "empty",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/empty")),
    },
    "field": {
      name: "field",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/field")),
    },
    "hover-card": {
      name: "hover-card",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/hover-card")),
    },
    "input": {
      name: "input",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/input")),
    },
    "input-group": {
      name: "input-group",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/input-group")),
    },
    "input-otp": {
      name: "input-otp",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/input-otp")),
    },
    "item": {
      name: "item",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/item")),
    },
    "kbd": {
      name: "kbd",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/kbd")),
    },
    "label": {
      name: "label",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/label")),
    },
    "menubar": {
      name: "menubar",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/menubar")),
    },
    "native-select": {
      name: "native-select",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/native-select")),
    },
    "navigation-menu": {
      name: "navigation-menu",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/navigation-menu")),
    },
    "pagination": {
      name: "pagination",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/pagination")),
    },
    "popover": {
      name: "popover",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/popover")),
    },
    "progress": {
      name: "progress",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/progress")),
    },
    "radio-group": {
      name: "radio-group",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/radio-group")),
    },
    "resizable": {
      name: "resizable",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/resizable")),
    },
    "scroll-area": {
      name: "scroll-area",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/scroll-area")),
    },
    "select": {
      name: "select",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/select")),
    },
    "separator": {
      name: "separator",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/separator")),
    },
    "sheet": {
      name: "sheet",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/sheet")),
    },
    "sidebar": {
      name: "sidebar",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/sidebar")),
    },
    "skeleton": {
      name: "skeleton",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/skeleton")),
    },
    "slider": {
      name: "slider",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/slider")),
    },
    "sonner": {
      name: "sonner",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/sonner")),
    },
    "spinner": {
      name: "spinner",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/spinner")),
    },
    "switch": {
      name: "switch",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/switch")),
    },
    "table": {
      name: "table",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/table")),
    },
    "tabs": {
      name: "tabs",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/tabs")),
    },
    "textarea": {
      name: "textarea",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/textarea")),
    },
    "toggle": {
      name: "toggle",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/toggle")),
    },
    "toggle-group": {
      name: "toggle-group",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/toggle-group")),
    },
    "tooltip": {
      name: "tooltip",
      type: "registry:ui",
      component: lazy(() => import("@/registry/new-york-v4/ui/tooltip")),
    },
    // Pro components
    "pro-base": {
      name: "pro-base",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/base/hooks/use-fullscreen.ts", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/button/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/base/button")),
    },
    "pro-fields": {
      name: "pro-fields",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/base/fields/shared/field.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/shared/calendar.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/input/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/input/money.ts", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/select/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/select/tree.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/checkbox/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/radio/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/date-picker/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/date-time-picker/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/upload/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/base/fields/array-field/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/base/fields/input")),
    },
    "pro-pagination": {
      name: "pro-pagination",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/pagination/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/pagination/index")),
    },
    "pro-list": {
      name: "pro-list",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/list/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/list/index")),
    },
    "pro-overlay": {
      name: "pro-overlay",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/overlay/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/overlay/index")),
    },
    "pro-form": {
      name: "pro-form",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/form/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/form/schema-render.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/form/validators.ts", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/form/index")),
    },
    "pro-table": {
      name: "pro-table",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/table/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/table/body.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/table/url-state.ts", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/table/index")),
    },
    "pro-editor": {
      name: "pro-editor",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/editor/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/editor/theme.ts", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/editor/theme-types.ts", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/editor/theme-worker.ts", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/editor/index")),
    },
    "pro-descriptions": {
      name: "pro-descriptions",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/descriptions/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/descriptions/index")),
    },
    "code-viewer": {
      name: "code-viewer",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/viewer/code/index.tsx", type: "registry:ui" },
        {
          path: "registry/new-york-v4/pro/viewer/code/highlight-types.ts",
          type: "registry:ui",
        },
        { path: "registry/new-york-v4/pro/viewer/code/highlighter.ts", type: "registry:ui" },
        {
          path: "registry/new-york-v4/pro/viewer/code/highlight-worker.ts",
          type: "registry:ui",
        },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/viewer/code")),
    },
    "diff-viewer": {
      name: "diff-viewer",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/viewer/diff/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/viewer/diff")),
    },
    "html-viewer": {
      name: "html-viewer",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/viewer/html/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/viewer/html")),
    },
    "image-viewer": {
      name: "image-viewer",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/viewer/image/index.tsx", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/viewer/image")),
    },
    "markdown-viewer": {
      name: "markdown-viewer",
      type: "registry:ui",
      files: [
        { path: "registry/new-york-v4/pro/viewer/markdown/index.tsx", type: "registry:ui" },
        { path: "registry/new-york-v4/pro/viewer/markdown/plugins.ts", type: "registry:ui" },
        {
          path: "registry/new-york-v4/pro/viewer/markdown/use-markdown-worker.ts",
          type: "registry:ui",
        },
        { path: "registry/new-york-v4/pro/viewer/markdown/worker.ts", type: "registry:ui" },
      ],
      component: lazy(() => import("@/registry/new-york-v4/pro/viewer/markdown")),
    },
  },
}
